const crypto = require("crypto");

const OUTBOUND_TIMEOUT_MS = Number(process.env.TVF_OUTBOUND_TIMEOUT_MS || 9000);
const POINT_TYPES = new Set(["bien", "commerce", "friche", "materiau", "partenaire", "projet", "signalement", "antenne", "autre"]);
const RELATED_TYPES = new Set(["none", "request", "case", "document", "procedure", "knowledge", "contact", "organization", "branch", "project"]);
const PRECISION_LEVELS = new Set(["exact", "rue", "quartier", "commune", "masque"]);
const VISIBILITY_LEVELS = new Set(["public", "interne", "confidentiel", "sensible"]);
const POINT_STATUSES = new Set(["actif", "a_verifier", "inactif", "archive"]);
const RISK_LEVELS = new Set(["faible", "modere", "eleve", "critique"]);
const ALERT_TYPES = new Set(["doublon", "proximite", "localisation_sensible", "precision_manquante", "priorite_territoriale"]);
const ALERT_STATUSES = new Set(["ouverte", "resolue", "ignoree"]);

function sendJson(res, statusCode, payload) { res.statusCode = statusCode; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(payload)); }
function clean(value, max = 1200) { if (typeof value !== "string") return ""; return value.replace(/\s+/g, " ").trim().slice(0, max); }
function cleanEnvToken(value, max = 3000) { return clean(value || "", max).replace(/^[`'\",;]+|[`'\",;]+$/g, "").replace(/\s+/g, ""); }
function cleanEnvUrl(value) { return clean(value || "", 600).replace(/^[`'\",;]+|[`'\",;]+$/g, ""); }
function normalizeSupabaseRestUrl(rawUrl) { const cleaned = cleanEnvUrl(rawUrl).replace(/\/+$/, ""); if (!cleaned) return ""; return cleaned.endsWith("/rest/v1") ? cleaned : `${cleaned}/rest/v1`; }
async function readJsonBody(req) { let body = ""; for await (const chunk of req) { body += chunk; if (body.length > 90 * 1024) throw Object.assign(new Error("Payload trop volumineux."), { statusCode: 413 }); } if (!body) return {}; try { return JSON.parse(body); } catch { throw Object.assign(new Error("JSON invalide."), { statusCode: 400 }); } }
function adminToken() { return cleanEnvToken(process.env.TVF_ADMIN_TOKEN || process.env.ADMIN_TOKEN || "", 3000); }
function adminCookieSignature() {
  const token = adminToken();
  if (!token) return "";
  return crypto.createHmac("sha256", token).update("tvf-os-admin-session-v1").digest("hex");
}
function cookieValue(req, name = "tvf_admin_session") {
  const cookieHeader = clean(req.headers.cookie || "", 6000);
  const cookies = cookieHeader.split(";").map((item) => item.trim());
  const found = cookies.find((item) => item.startsWith(`${name}=`));
  return found ? cleanEnvToken(decodeURIComponent(found.slice(name.length + 1)), 3000) : "";
}
function tokenFromRequest(req) {
  const expectedCookie = adminCookieSignature();
  const receivedCookie = cookieValue(req);
  if (expectedCookie && receivedCookie && safeEqual(receivedCookie, expectedCookie)) return adminToken();
  const authorization = clean(req.headers.authorization || "", 4000);
  if (authorization.toLowerCase().startsWith("bearer ")) {
    const bearer = cleanEnvToken(authorization.slice(7), 3000);
    if (bearer) return bearer;
  }
  return cleanEnvToken(req.headers["x-admin-token"] || "", 3000);
}
function safeEqual(a, b) { if (!a || !b) return false; const left = Buffer.from(a); const right = Buffer.from(b); if (left.length !== right.length) return false; return crypto.timingSafeEqual(left, right); }
function requireAdmin(req) { const expected = adminToken(); if (!expected) throw Object.assign(new Error("Back-office non configure : ajoutez TVF_ADMIN_TOKEN dans Vercel."), { statusCode: 503, code: "ADMIN_TOKEN_MISSING" }); if (!safeEqual(tokenFromRequest(req), expected)) throw Object.assign(new Error("Acces admin refuse."), { statusCode: 401, code: "ADMIN_UNAUTHORIZED" }); }
function supabaseConfig() { const restUrl = normalizeSupabaseRestUrl(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL); const key = cleanEnvToken(process.env.SUPABASE_SERVICE_ROLE_KEY || "", 3000); if (!restUrl || !key) throw Object.assign(new Error("Supabase admin non configure : SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY sont requis."), { statusCode: 503, code: "SUPABASE_ADMIN_NOT_CONFIGURED" }); return { restUrl, key }; }
function supabaseHeaders(key, extra = {}) { const headers = { apikey: key, "Content-Type": "application/json", ...extra }; if (!key.startsWith("sb_")) headers.Authorization = `Bearer ${key}`; return headers; }
async function fetchWithTimeout(url, options = {}) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), OUTBOUND_TIMEOUT_MS); try { return await fetch(url, { ...options, signal: controller.signal }); } finally { clearTimeout(timeout); } }
async function supabaseRequest(path, options = {}) { const { restUrl, key } = supabaseConfig(); const response = await fetchWithTimeout(`${restUrl}/${path}`, { ...options, headers: supabaseHeaders(key, options.headers || {}) }); const text = await response.text(); if (!response.ok) throw Object.assign(new Error("Requete Supabase impossible."), { statusCode: 502, details: text }); return text ? JSON.parse(text) : null; }
function queryUrl(req) { return new URL(req.url, "https://admin.local"); }
function normalizeForMatch(value) { return String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function validateEnum(set, value, message) { if (value && !set.has(value)) throw Object.assign(new Error(message), { statusCode: 400 }); }
function validateUuid(value, label = "Identifiant") { const cleaned = clean(value || "", 80); if (cleaned && !/^[0-9a-f-]{32,36}$/i.test(cleaned)) throw Object.assign(new Error(`${label} invalide.`), { statusCode: 400 }); return cleaned || null; }
function numberValue(value, fallback = null) { const num = Number(value); return Number.isFinite(num) ? num : fallback; }
function inferPointType(input) { const text = normalizeForMatch([input.point_type, input.label, input.description, input.address_text].join(" ")); if (/materiau|stock|reemploi|mobilier/.test(text)) return "materiau"; if (/commerce|boutique|local commercial/.test(text)) return "commerce"; if (/friche|terrain/.test(text)) return "friche"; if (/partenaire|mairie|association|entreprise|financeur/.test(text)) return "partenaire"; if (/projet|chantier|activation/.test(text)) return "projet"; if (/signalement|alerte|observation/.test(text)) return "signalement"; if (/antenne|base locale/.test(text)) return "antenne"; return "bien"; }
function defaultLayerColor(type) { return { bien: "#2f7d32", commerce: "#0e6f88", friche: "#8f5b24", materiau: "#8a6f15", partenaire: "#355f91", projet: "#6f4aa8", signalement: "#b43b2f", antenne: "#183f22", autre: "#667085" }[type] || "#667085"; }
function maskCoordinates(lat, lon, precision) { if (precision === "masque") return { latitude: null, longitude: null }; const decimals = precision === "commune" ? 2 : precision === "quartier" ? 3 : precision === "rue" ? 4 : 6; return { latitude: lat == null ? null : Number(lat.toFixed(decimals)), longitude: lon == null ? null : Number(lon.toFixed(decimals)) }; }
function distanceMeters(a, b) { if (a.latitude == null || a.longitude == null || b.latitude == null || b.longitude == null) return null; const rad = Math.PI / 180; const lat1 = Number(a.latitude) * rad; const lat2 = Number(b.latitude) * rad; const dLat = (Number(b.latitude) - Number(a.latitude)) * rad; const dLon = (Number(b.longitude) - Number(a.longitude)) * rad; const s = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return Math.round(6371000 * 2 * Math.atan2(Math.sqrt(s), Math.sqrt(1 - s))); }
function priorityScore(input) { let score = 30; const type = clean(input.point_type || inferPointType(input), 80); const risk = clean(input.risk_level || "modere", 80); const visibility = clean(input.visibility_level || "interne", 80); if (["bien", "commerce", "friche"].includes(type)) score += 18; if (type === "materiau") score += 12; if (type === "signalement") score += 15; if (risk === "critique") score += 28; else if (risk === "eleve") score += 18; else if (risk === "modere") score += 8; if (visibility === "sensible") score += 8; if (clean(input.status || "") === "a_verifier") score += 7; return Math.max(0, Math.min(100, score)); }
function assistantForPoint(row, neighbors = []) { const missing = []; if (row.latitude == null || row.longitude == null) missing.push("coordonnees"); if (!row.address_text) missing.push("adresse"); if (!row.related_object_id && row.related_object_type !== "none") missing.push("objet lie"); if (row.precision_level === "exact" && row.visibility_level === "sensible") missing.push("masquage coordonnees sensibles"); const close = neighbors.filter((item) => item.id !== row.id).map((item) => ({ id: item.id, label: item.label, distance_meters: distanceMeters(row, item) })).filter((item) => item.distance_meters != null && item.distance_meters <= 150).slice(0, 5); return { missing_fields: missing, priority_score: row.priority_score ?? priorityScore(row), suggested_precision: row.visibility_level === "sensible" ? "quartier" : row.precision_level, close_points: close, summary: row.ai_summary || `${row.label || "Point"} - ${row.point_type || "carte"}, statut ${row.status || "actif"}.` }; }
function enrichPoint(row, allRows = []) { return { ...row, assistant: assistantForPoint(row || {}, allRows || []) }; }
function pointPayload(input, partial = false) { const type = clean(input.point_type || "", 80) || (!partial ? inferPointType(input) : ""); const relatedType = clean(input.related_object_type || "none", 80) || "none"; const precision = clean(input.precision_level || "", 80) || (!partial ? "quartier" : ""); const visibility = clean(input.visibility_level || "", 80) || (!partial ? "interne" : ""); const status = clean(input.status || "", 80) || (!partial ? "a_verifier" : ""); const risk = clean(input.risk_level || "", 80) || (!partial ? "modere" : ""); validateEnum(POINT_TYPES, type, "Type de point invalide."); validateEnum(RELATED_TYPES, relatedType, "Type d'objet lie invalide."); validateEnum(PRECISION_LEVELS, precision, "Niveau de precision invalide."); validateEnum(VISIBILITY_LEVELS, visibility, "Niveau de visibilite invalide."); validateEnum(POINT_STATUSES, status, "Statut cartographique invalide."); validateEnum(RISK_LEVELS, risk, "Niveau de risque invalide."); const rawLat = numberValue(input.latitude, null); const rawLon = numberValue(input.longitude, null); if (rawLat != null && (rawLat < -90 || rawLat > 90)) throw Object.assign(new Error("Latitude invalide."), { statusCode: 400 }); if (rawLon != null && (rawLon < -180 || rawLon > 180)) throw Object.assign(new Error("Longitude invalide."), { statusCode: 400 }); const masked = maskCoordinates(rawLat, rawLon, precision);
  const fields = { branch_id: validateUuid(input.branch_id || "", "Antenne"), point_type: type, related_object_type: relatedType, related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), latitude: masked.latitude, longitude: masked.longitude, precision_level: precision, visibility_level: visibility, label: clean(input.label || "", 260), description: clean(input.description || "", 2400), address_text: clean(input.address_text || "", 700), city: clean(input.city || "", 160), department: clean(input.department || "", 120), region: clean(input.region || "", 120), status, risk_level: risk, source_label: clean(input.source_label || input.source || "TVF OS", 180), created_by: clean(input.created_by || "TVF OS", 180), ai_summary: clean(input.ai_summary || "", 1000) };
  if (!partial && !fields.label) throw Object.assign(new Error("Libelle du point requis."), { statusCode: 400 }); fields.priority_score = priorityScore({ ...input, point_type: type, risk_level: risk, visibility_level: visibility, status }); const payload = {}; Object.entries(fields).forEach(([key, value]) => { if (!partial || Object.prototype.hasOwnProperty.call(input, key) || ["point_type", "related_object_type", "precision_level", "visibility_level", "status", "risk_level"].includes(key)) { if (value !== "" && value !== undefined) payload[key] = value; else if (partial && Object.prototype.hasOwnProperty.call(input, key)) payload[key] = null; } }); if (!payload.ai_summary && payload.label) payload.ai_summary = `${payload.label} - ${type}, priorite ${payload.priority_score}.`; return payload; }
function geocodeCheckPayload(input) { return { point_id: validateUuid(input.point_id || "", "Point"), input_address: clean(input.input_address || input.address_text || "", 700), normalized_address: clean(input.normalized_address || input.address_text || "", 700), confidence: Math.max(0, Math.min(1, numberValue(input.confidence, 0.5))), status: clean(input.status || "propose", 80), notes: clean(input.notes || "Geocodage controle manuellement requis.", 1000) }; }
function alertPayload(input) { const type = clean(input.alert_type || "priorite_territoriale", 80); validateEnum(ALERT_TYPES, type, "Type d'alerte invalide."); return { point_id: validateUuid(input.point_id || "", "Point"), related_point_id: validateUuid(input.related_point_id || "", "Point lie"), alert_type: type, severity: clean(input.severity || "moyenne", 80), message: clean(input.message || "Alerte cartographique a verifier.", 1200), status: clean(input.status || "ouverte", 80) }; }
async function listPoints(req) { const url = queryUrl(req); const params = new URLSearchParams({ select: "*", order: "updated_at.desc" }); params.set("limit", String(Math.min(Math.max(Number(url.searchParams.get("limit") || 180), 1), 500))); const type = clean(url.searchParams.get("point_type") || "", 80); const status = clean(url.searchParams.get("status") || "", 80); const visibility = clean(url.searchParams.get("visibility_level") || "", 80); const q = clean(url.searchParams.get("q") || "", 160).replace(/[*,()]/g, " "); if (type && type !== "all" && POINT_TYPES.has(type)) params.set("point_type", `eq.${type}`); if (status && status !== "all" && POINT_STATUSES.has(status)) params.set("status", `eq.${status}`); if (visibility && visibility !== "all" && VISIBILITY_LEVELS.has(visibility)) params.set("visibility_level", `eq.${visibility}`); if (q) params.set("or", `(label.ilike.*${q}*,address_text.ilike.*${q}*,city.ilike.*${q}*,description.ilike.*${q}*)`); const rows = await supabaseRequest(`map_points?${params.toString()}`); return (rows || []).map((row) => enrichPoint(row, rows || [])); }
async function listLayers() { const rows = await supabaseRequest("map_layers?select=*&order=sort_order.asc"); return rows || []; }
async function listAlerts(req) { const url = queryUrl(req); const params = new URLSearchParams({ select: "*", order: "created_at.desc", limit: String(Math.min(Math.max(Number(url.searchParams.get("limit") || 80), 1), 200)) }); const status = clean(url.searchParams.get("status") || "", 80); if (status && status !== "all" && ALERT_STATUSES.has(status)) params.set("status", `eq.${status}`); return supabaseRequest(`map_spatial_alerts?${params.toString()}`); }
async function dashboardMap() { const [points, alerts, layers] = await Promise.all([supabaseRequest("map_points?select=id,point_type,status,visibility_level,risk_level,priority_score,latitude,longitude&limit=2000"), supabaseRequest("map_spatial_alerts?select=id,status,severity,alert_type&limit=1000"), listLayers()]); return { points_total: points.length, active_points: points.filter((p) => p.status === "actif").length, to_verify: points.filter((p) => p.status === "a_verifier").length, sensitive: points.filter((p) => p.visibility_level === "sensible").length, high_priority: points.filter((p) => Number(p.priority_score || 0) >= 70).length, open_alerts: alerts.filter((a) => a.status === "ouverte").length, geolocated: points.filter((p) => p.latitude != null && p.longitude != null).length, layers_enabled: layers.filter((l) => l.enabled !== false).length, by_type: Object.fromEntries([...POINT_TYPES].map((type) => [type, points.filter((p) => p.point_type === type).length])) }; }
async function createPoint(input) { const payload = pointPayload(input); const rows = await supabaseRequest("map_points?select=*", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); const point = rows?.[0]; await createAutomaticAlerts(point).catch(() => {}); return enrichPoint(point, [point]); }
async function updatePoint(input) { const id = validateUuid(input.id || "", "Point"); if (!id) throw Object.assign(new Error("Point requis."), { statusCode: 400 }); const payload = pointPayload(input, true); const rows = await supabaseRequest(`map_points?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); const point = rows?.[0]; await createAutomaticAlerts(point).catch(() => {}); return enrichPoint(point, [point]); }
async function createAutomaticAlerts(point) { if (!point) return []; const alerts = []; if (point.visibility_level === "sensible" && point.precision_level === "exact") alerts.push(alertPayload({ point_id: point.id, alert_type: "localisation_sensible", severity: "haute", message: "Point sensible avec precision exacte : verifier le masquage." })); if (point.latitude == null || point.longitude == null) alerts.push(alertPayload({ point_id: point.id, alert_type: "precision_manquante", severity: "moyenne", message: "Coordonnees absentes : geocodage controle necessaire." })); if (Number(point.priority_score || 0) >= 75) alerts.push(alertPayload({ point_id: point.id, alert_type: "priorite_territoriale", severity: "haute", message: "Point a priorite territoriale elevee." })); if (!alerts.length) return []; const rows = await supabaseRequest("map_spatial_alerts?select=*", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(alerts) }); return rows || []; }
async function createGeocodeCheck(input) { const payload = geocodeCheckPayload(input); if (!payload.point_id || !payload.input_address) throw Object.assign(new Error("Controle geocodage incomplet."), { statusCode: 400 }); const rows = await supabaseRequest("map_geocode_checks?select=*", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function updateAlert(input) { const id = validateUuid(input.id || "", "Alerte"); if (!id) throw Object.assign(new Error("Alerte requise."), { statusCode: 400 }); const status = clean(input.status || "", 80); validateEnum(ALERT_STATUSES, status, "Statut d'alerte invalide."); const rows = await supabaseRequest(`map_spatial_alerts?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ status, reviewed_by: clean(input.reviewed_by || "TVF OS", 180), reviewed_at: new Date().toISOString() }) }); return rows?.[0] || null; }
async function handler(req, res) { if (req.method === "OPTIONS") { res.statusCode = 204; res.end(); return; } try { requireAdmin(req); const url = queryUrl(req); const entity = clean(url.searchParams.get("entity") || "points", 80); if (req.method === "GET") { if (entity === "dashboard") return sendJson(res, 200, { ok: true, dashboard: await dashboardMap() }); if (entity === "layers") return sendJson(res, 200, { ok: true, layers: await listLayers() }); if (entity === "alerts") return sendJson(res, 200, { ok: true, alerts: await listAlerts(req) }); return sendJson(res, 200, { ok: true, points: await listPoints(req), layers: await listLayers() }); } const data = await readJsonBody(req); const type = clean(data.type || "point", 80); if (req.method === "POST") { if (type === "point") return sendJson(res, 201, { ok: true, point: await createPoint(data) }); if (type === "geocode_check") return sendJson(res, 201, { ok: true, geocode_check: await createGeocodeCheck(data) }); }
    if (req.method === "PATCH") { if (type === "point") return sendJson(res, 200, { ok: true, point: await updatePoint(data) }); if (type === "alert") return sendJson(res, 200, { ok: true, alert: await updateAlert(data) }); }
    sendJson(res, 405, { ok: false, error: "Methode non autorisee." }); } catch (error) { const statusCode = error.statusCode || 500; sendJson(res, statusCode, { ok: false, error: statusCode >= 500 ? "Cartographie temporairement non chargee : vérifiez la configuration Supabase du module." : error.message, code: error.code || undefined, details: process.env.NODE_ENV === "development" ? error.details || error.message : undefined }); } }
module.exports = handler;
module.exports._private = { normalizeSupabaseRestUrl, inferPointType, defaultLayerColor, maskCoordinates, distanceMeters, priorityScore, assistantForPoint, pointPayload, geocodeCheckPayload, alertPayload };
