const RISKS_TOKEN_KEY = "tvfAdminToken";
const statusLabels = { open: "Ouvert", mitigating: "Mitigation", blocked: "Bloque", accepted: "Accepte", resolved: "Resolu", closed: "Clos", archive: "Archive", missing: "Manquant", to_review: "A verifier", valid: "Valide", expired: "Expire", rejected: "Refuse", waived: "Ignore", new: "Nouveau", triage: "Qualification", investigating: "Investigation", corrective_action: "Action corrective", pending: "En attente", revoked: "Revoque" };
const viewLabels = { risks: "Risques", checks: "Conformite", incidents: "Incidents", consents: "Autorisations", audit: "Audit" };
const entityByView = { risks: "risks", checks: "checks", incidents: "incidents", consents: "consents", audit: "audit" };

const loginSection = document.querySelector("[data-risks-login]");
const appSection = document.querySelector("[data-risks-app]");
const tokenForm = document.querySelector("[data-risks-token-form]");
const loginStatus = document.querySelector("[data-risks-login-status]");
const filtersForm = document.querySelector("[data-risks-filters]");
const kpisEl = document.querySelector("[data-risks-kpis]");
const controlEl = document.querySelector("[data-risks-control]");
const listEl = document.querySelector("[data-risks-list]");
const detailEl = document.querySelector("[data-risks-detail]");
const countEl = document.querySelector("[data-risks-count]");
const listCountEl = document.querySelector("[data-risks-list-count]");
const listTitleEl = document.querySelector("[data-risks-list-title]");
const emptyEl = document.querySelector("[data-risks-empty]");
const aiScoreEl = document.querySelector("[data-risks-ai-score]");
const aiSummaryEl = document.querySelector("[data-risks-ai-summary]");
const aiGridEl = document.querySelector("[data-risks-ai-grid]");
const tabs = document.querySelectorAll("[data-risks-view]");
const createButton = document.querySelector("[data-risks-create]");
const refreshButton = document.querySelector("[data-risks-refresh]");
const exportButton = document.querySelector("[data-risks-export]");
const logoutButton = document.querySelector("[data-risks-logout]");
const modal = document.querySelector("[data-risks-modal]");
const modalForm = document.querySelector("[data-risks-form]");
const closeModalButtons = document.querySelectorAll("[data-risks-close-modal]");
let view = "risks";
let dashboard = null;
let data = { risks: [], checks: [], incidents: [], consents: [], audit: [] };
let selectedId = null;
let debounceTimer;

function token() { try { return sessionStorage.getItem(RISKS_TOKEN_KEY) || ""; } catch { return ""; } }
function setToken(value) { try { if (value) sessionStorage.setItem(RISKS_TOKEN_KEY, value); else sessionStorage.removeItem(RISKS_TOKEN_KEY); } catch {} }
function showApp() { if (loginSection) loginSection.hidden = true; if (appSection) appSection.hidden = false; }
function showLogin() { if (loginSection) loginSection.hidden = false; if (appSection) appSection.hidden = true; }
function setStatus(message, type = "info") { if (!loginStatus) return; loginStatus.hidden = !message; loginStatus.textContent = message; loginStatus.dataset.status = type; }
function notify(message, type = "info") { if (window.tvfAdminNotice) window.tvfAdminNotice(message, type); else if (type === "error") console.error(message); else console.log(message); }
function notifyError(error, fallback = "Action impossible pour le moment.") { notify(error?.message || fallback, "error"); }
function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function label(value) { return statusLabels[value] || value || "Non renseigne"; }
function formatDate(value) { if (!value) return "Non renseigne"; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short" }).format(date); }
function currentItems() { return data[view] || []; }
function selectedItem() { return currentItems().find((item) => item.id === selectedId) || currentItems()[0] || null; }
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const text = await response.text(); const result = text ? JSON.parse(text) : { ok: response.ok }; if (!response.ok || result.ok === false) { const error = new Error(result.error || "Action impossible."); error.status = response.status; throw error; } return result; }
function filtersParams(entity) { const formData = new FormData(filtersForm); const params = new URLSearchParams({ entity, limit: "260" }); const q = String(formData.get("q") || "").trim(); const status = String(formData.get("status") || "").trim(); if (q) params.set("q", q); if (status && status !== "all") params.set("status", status); return params; }
async function loadAll() {
  if (countEl) countEl.textContent = "Chargement des risques...";
  const overview = await api("/api/admin-risks?entity=dashboard");
  const [risks, checks, incidents, consents, audit] = await Promise.all([
    api(`/api/admin-risks?${filtersParams("risks").toString()}`), api(`/api/admin-risks?${filtersParams("checks").toString()}`), api(`/api/admin-risks?${filtersParams("incidents").toString()}`), api(`/api/admin-risks?${filtersParams("consents").toString()}`), api("/api/admin-risks?entity=audit")
  ]);
  dashboard = overview.dashboard || {};
  data = { risks: risks.risks || [], checks: checks.checks || [], incidents: incidents.incidents || [], consents: consents.consents || [], audit: audit.audit_logs || [] };
  if (!currentItems().some((item) => item.id === selectedId)) selectedId = currentItems()[0]?.id || null;
  renderAll();
}
function renderAll() { renderKpis(); renderControlPanel(); renderAssistant(); renderTabs(); renderList(); renderDetail(); }
function renderKpis() { if (!kpisEl) return; kpisEl.innerHTML = `<article><span>Score</span><strong>${dashboard?.compliance_score || 0}%</strong><small>conformite</small></article><article data-tone="danger"><span>Blocages</span><strong>${dashboard?.blocking_checks || 0}</strong><small>controles</small></article><article data-tone="warning"><span>Risques ouverts</span><strong>${dashboard?.open_risks || 0}</strong><small>${dashboard?.critical_risks || 0} critiques/eleves</small></article><article><span>Incidents</span><strong>${dashboard?.open_incidents || 0}</strong><small>ouverts</small></article><article data-tone="info"><span>Autorisations</span><strong>${dashboard?.pending_consents || 0}</strong><small>a regulariser</small></article>`; if (countEl) countEl.textContent = `${dashboard?.open_risks || 0} risque(s) ouvert(s), ${dashboard?.blocking_checks || 0} blocage(s), ${dashboard?.open_incidents || 0} incident(s).`; }
function renderControlPanel() {
  if (!controlEl || !dashboard) return;
  const score = Number(dashboard.compliance_score || 0);
  const blocking = Number(dashboard.blocking_checks || 0);
  const openRisks = Number(dashboard.open_risks || 0);
  const incidents = Number(dashboard.open_incidents || 0);
  const consents = Number(dashboard.pending_consents || 0);
  const nextDecision = blocking ? "Lever les controles bloquants" : incidents ? "Traiter les incidents" : openRisks ? "Reduire les risques ouverts" : consents ? "Regulariser les autorisations" : "Maintenir la conformite";
  const status = blocking || incidents ? "Blocage a traiter" : score < 70 ? "Conformite a renforcer" : "Controle stable";
  controlEl.innerHTML = `<div class="admin-panel-head"><div><p class="section-kicker">Priorite conformite</p><h3>Eviter les blocages avant action terrain</h3><p>Cette synthese met en avant les risques juridiques, RGPD, assurances, securite et pieces bloquantes avant engagement.</p></div><strong>${escapeHtml(status)}</strong></div><div class="risks-control-grid"><article><span>Decision suivante</span><strong>${escapeHtml(nextDecision)}</strong><small>priorite</small></article><article><span>Score</span><strong>${escapeHtml(score)}%</strong><small>conformite</small></article><article><span>Blocages</span><strong>${escapeHtml(blocking)}</strong><small>controles</small></article><article><span>Incidents</span><strong>${escapeHtml(incidents)}</strong><small>ouverts</small></article><article><span>Autorisations</span><strong>${escapeHtml(consents)}</strong><small>a regulariser</small></article></div><div class="risks-control-links"><a class="btn secondary" href="admin-governance">Decision</a><a class="btn secondary" href="admin-documents">Pieces</a><a class="btn secondary" href="admin-work">Taches</a><a class="btn secondary" href="admin-dossiers">Dossiers</a><a class="btn secondary" href="admin-users">Acces</a></div>`;
}function renderAssistant() { const item = selectedItem(); const assistant = item?.assistant || dashboard?.assistant || {}; if (aiScoreEl) aiScoreEl.textContent = item?.assistant?.level || `${dashboard?.compliance_score || 0}%`; if (aiSummaryEl) aiSummaryEl.textContent = assistant.summary || dashboard?.assistant?.summary || "Aucune analyse disponible."; if (!aiGridEl) return; const priorities = assistant.recommended_actions || dashboard?.assistant?.priorities || []; aiGridEl.innerHTML = priorities.length ? priorities.slice(0, 4).map((action) => `<div><span>Action</span><strong>${escapeHtml(action)}</strong></div>`).join("") : `<div><span>Action</span><strong>Controle a jour</strong></div>`; }
function renderTabs() { tabs.forEach((button) => button.classList.toggle("is-active", button.dataset.risksView === view)); }
function titleFor(item) { return item.title || item.person_name || item.action || "Element"; }
function subFor(item) { return item.risk_key || item.check_key || item.incident_key || item.consent_type || item.object_type || item.owner_name || ""; }
function itemCard(item) { const tone = item.assistant?.should_block || item.blocking ? " is-risk" : ""; return `<button class="admin-request risks-card${item.id === selectedId ? " is-active" : ""}${tone}" type="button" data-risks-id="${escapeHtml(item.id)}"><span class="admin-request-head"><strong>${escapeHtml(titleFor(item))}</strong><small>${escapeHtml(label(item.status || item.severity))}</small></span><span>${escapeHtml(subFor(item))}</span><span class="admin-request-sub">${escapeHtml(item.description || item.notes || item.mitigation_plan || item.ai_summary || "")}</span><span class="admin-badges"><em data-kind="priority">${escapeHtml(item.severity || item.status || item.assistant?.level || "")}</em><em data-kind="category">${escapeHtml(formatDate(item.due_at || item.occurred_at || item.created_at))}</em></span></button>`; }
function renderList() { if (listTitleEl) listTitleEl.textContent = viewLabels[view]; if (listCountEl) listCountEl.textContent = String(currentItems().length); if (emptyEl) emptyEl.hidden = currentItems().length > 0; if (listEl) listEl.innerHTML = currentItems().map(itemCard).join(""); }
function statusOptions(current) { const values = view === "risks" ? ["open", "mitigating", "blocked", "accepted", "resolved", "closed", "archive"] : view === "checks" ? ["missing", "to_review", "valid", "expired", "rejected", "waived", "archive"] : view === "incidents" ? ["new", "triage", "investigating", "corrective_action", "closed", "archive"] : ["pending", "valid", "expired", "revoked", "rejected", "archive"]; return values.map((value) => `<option value="${value}" ${value === current ? "selected" : ""}>${escapeHtml(label(value))}</option>`).join(""); }
function renderDetail() { const item = selectedItem(); if (!detailEl) return; if (!item) { detailEl.innerHTML = `<p class="form-note">Aucun element selectionne.</p>`; return; } const assistant = item.assistant || {}; const type = view === "risks" ? "risk" : view === "checks" ? "check" : view === "incidents" ? "incident" : view === "consents" ? "consent" : "audit"; const editable = view !== "audit"; detailEl.innerHTML = `<div class="admin-panel-head"><div><p class="section-kicker">${escapeHtml(viewLabels[view])}</p><h2>${escapeHtml(titleFor(item))}</h2><p>${escapeHtml(subFor(item))}</p></div><span>${escapeHtml(label(item.status || item.severity))}</span></div><section class="risks-readiness"><article><span>Niveau</span><strong>${escapeHtml(assistant.level || item.severity || "--")}</strong></article><article><span>Score</span><strong>${escapeHtml(assistant.score ?? "--")}</strong></article><article><span>Blocage</span><strong>${assistant.should_block || item.blocking ? "Oui" : "Non"}</strong></article><article><span>Echeance</span><strong>${escapeHtml(formatDate(item.due_at || item.valid_until || item.occurred_at))}</strong></article></section>${editable ? `<form class="risks-detail-form" data-risks-detail-form><input type="hidden" name="id" value="${escapeHtml(item.id)}"><input type="hidden" name="type" value="${type}"><label>Titre<input name="title" value="${escapeHtml(titleFor(item))}"></label><label>Statut<select name="status">${statusOptions(item.status)}</select></label><label>Responsable<input name="owner_name" value="${escapeHtml(item.owner_name || "")}"></label><label>Severite<input name="severity" value="${escapeHtml(item.severity || "")}"></label><label class="risks-wide-field">Description<textarea name="summary" rows="5">${escapeHtml(item.description || item.notes || item.mitigation_plan || "")}</textarea></label><button class="btn primary" type="submit">Enregistrer</button></form>` : `<pre>${escapeHtml(JSON.stringify(item, null, 2))}</pre>`}`; }
function openModal() { if (modal) modal.hidden = false; }
function closeModal() { if (modal) modal.hidden = true; modalForm?.reset(); }
function payloadFromForm(form) { const data = new FormData(form); const payload = {}; data.forEach((value, key) => { const text = String(value || "").trim(); if (text) payload[key] = text; }); if (payload.type === "check") { payload.check_type = payload.risk_type || "rgpd"; payload.notes = payload.summary || ""; payload.blocking = payload.severity === "critical" ? "true" : "false"; } if (payload.type === "incident") { payload.incident_type = payload.risk_type || "operational"; payload.description = payload.summary || ""; } if (payload.type === "consent") { payload.person_name = payload.title || "Personne concernee"; payload.notes = payload.summary || ""; } if (payload.type === "risk") { payload.description = payload.summary || ""; payload.mitigation_plan = payload.summary || ""; } return payload; }
async function createItem(event) { event.preventDefault(); await api("/api/admin-risks", { method: "POST", body: JSON.stringify(payloadFromForm(modalForm)) }); closeModal(); await loadAll(); notify("Element risque cree.", "success"); }
async function saveDetail(form) { const payload = Object.fromEntries(new FormData(form)); if (payload.type === "check") payload.notes = payload.summary; if (payload.type === "incident") payload.description = payload.summary; if (payload.type === "consent") { payload.person_name = payload.title; payload.notes = payload.summary; } if (payload.type === "risk") { payload.description = payload.summary; payload.mitigation_plan = payload.summary; } await api("/api/admin-risks", { method: "PATCH", body: JSON.stringify(payload) }); await loadAll(); notify("Element risque enregistre.", "success"); }
function exportCsv() { const rows = [["Vue", "Titre", "Statut", "Reference"], ...currentItems().map((item) => [viewLabels[view], titleFor(item), label(item.status || item.severity), subFor(item)])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `risques-tvf-os-${view}-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); notify("Export risques prepare.", "success"); }
function bindEvents() { tokenForm?.addEventListener("submit", async (event) => { event.preventDefault(); const value = String(new FormData(tokenForm).get("token") || "").trim(); if (!value) return setStatus("Entrez le token admin.", "error"); setToken(value); try { showApp(); await loadAll(); setStatus(""); } catch (error) { setToken(""); showLogin(); setStatus(error.status === 401 ? "Token admin invalide." : error.message, "error"); } }); filtersForm?.addEventListener("input", () => { clearTimeout(debounceTimer); debounceTimer = setTimeout(() => loadAll().catch((e) => notifyError(e)), 260); }); filtersForm?.addEventListener("change", () => loadAll().catch((e) => notifyError(e))); tabs.forEach((button) => button.addEventListener("click", () => { view = button.dataset.risksView || "risks"; selectedId = currentItems()[0]?.id || null; renderAll(); })); refreshButton?.addEventListener("click", () => loadAll().catch((e) => notifyError(e))); createButton?.addEventListener("click", openModal); exportButton?.addEventListener("click", exportCsv); logoutButton?.addEventListener("click", () => { setToken(""); window.location.href = "admin"; }); closeModalButtons.forEach((button) => button.addEventListener("click", closeModal)); modal?.addEventListener("click", (event) => { if (event.target === modal) closeModal(); }); modalForm?.addEventListener("submit", createItem); listEl?.addEventListener("click", (event) => { const button = event.target.closest("[data-risks-id]"); if (!button) return; selectedId = button.dataset.risksId; renderAll(); }); detailEl?.addEventListener("submit", (event) => { const form = event.target.closest("[data-risks-detail-form]"); if (!form) return; event.preventDefault(); saveDetail(form).catch((e) => notifyError(e)); }); }

bindEvents();
if (token()) { showApp(); loadAll().catch((error) => { setToken(""); showLogin(); setStatus(error.status === 401 ? "Session expiree ou token invalide." : error.message, "error"); }); } else { showLogin(); }
