const EMAILS_TOKEN_KEY = "tvfAdminToken";
const statusLabels = { new: "Nouveau", analyzed: "Analyse", to_reply: "A repondre", waiting_info: "Infos manquantes", converted: "Converti", closed: "Clos", archive: "Archive", proposed: "Propose", accepted: "Accepte", modified: "Modifie", rejected: "Refuse", applied: "Applique", todo: "A faire", doing: "En cours", waiting: "Attente", done: "Termine", cancelled: "Annule" };
const viewLabels = { messages: "E-mails", suggestions: "Suggestions IA", tasks: "Taches", events: "Evenements" };
const loginSection = document.querySelector("[data-emails-login]");
const appSection = document.querySelector("[data-emails-app]");
const tokenForm = document.querySelector("[data-emails-token-form]");
const loginStatus = document.querySelector("[data-emails-login-status]");
const filtersForm = document.querySelector("[data-emails-filters]");
const kpisEl = document.querySelector("[data-emails-kpis]");
const listEl = document.querySelector("[data-emails-list]");
const detailEl = document.querySelector("[data-emails-detail]");
const countEl = document.querySelector("[data-emails-count]");
const listCountEl = document.querySelector("[data-emails-list-count]");
const listTitleEl = document.querySelector("[data-emails-list-title]");
const emptyEl = document.querySelector("[data-emails-empty]");
const aiScoreEl = document.querySelector("[data-emails-ai-score]");
const aiSummaryEl = document.querySelector("[data-emails-ai-summary]");
const aiGridEl = document.querySelector("[data-emails-ai-grid]");
const tabs = document.querySelectorAll("[data-emails-view]");
const createButton = document.querySelector("[data-emails-create]");
const refreshButton = document.querySelector("[data-emails-refresh]");
const exportButton = document.querySelector("[data-emails-export]");
const logoutButton = document.querySelector("[data-emails-logout]");
const modal = document.querySelector("[data-emails-modal]");
const modalForm = document.querySelector("[data-emails-form]");
const closeModalButtons = document.querySelectorAll("[data-emails-close-modal]");
let view = "messages";
let dashboard = null;
let data = { messages: [], suggestions: [], tasks: [], events: [] };
let selectedId = null;
let debounceTimer;
function token() { try { return sessionStorage.getItem(EMAILS_TOKEN_KEY) || ""; } catch { return ""; } }
function setToken(value) { try { if (value) sessionStorage.setItem(EMAILS_TOKEN_KEY, value); else sessionStorage.removeItem(EMAILS_TOKEN_KEY); } catch {} }
function showApp() { if (loginSection) loginSection.hidden = true; if (appSection) appSection.hidden = false; }
function showLogin() { if (loginSection) loginSection.hidden = false; if (appSection) appSection.hidden = true; }
function setStatus(message, type = "info") { if (!loginStatus) return; loginStatus.hidden = !message; loginStatus.textContent = message; loginStatus.dataset.status = type; }
function notify(message, type = "info") { if (window.tvfAdminNotice) window.tvfAdminNotice(message, type); else if (type === "error") console.error(message); else console.log(message); }
function notifyError(error, fallback = "Action impossible pour le moment.") { notify(error?.message || fallback, "error"); }
function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function label(value) { return statusLabels[value] || value || "Non renseigne"; }
function formatDate(value) { if (!value) return "Non renseigne"; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(date); }
function currentItems() { return data[view] || []; }
function selectedItem() { return currentItems().find((item) => item.id === selectedId) || currentItems()[0] || null; }
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const text = await response.text(); const result = text ? JSON.parse(text) : { ok: response.ok }; if (!response.ok || result.ok === false) { const error = new Error(result.error || "Action impossible."); error.status = response.status; throw error; } return result; }
function filtersParams(entity) { const formData = new FormData(filtersForm); const params = new URLSearchParams({ entity, limit: "240" }); const q = String(formData.get("q") || "").trim(); const status = String(formData.get("status") || "").trim(); if (q && entity === "messages") params.set("q", q); if (status && status !== "all") params.set("status", status); return params; }
async function loadAll() { if (countEl) countEl.textContent = "Chargement des e-mails..."; const overview = await api("/api/admin-emails?entity=dashboard"); const [messages, suggestions, tasks, events] = await Promise.all([api(`/api/admin-emails?${filtersParams("messages").toString()}`), api("/api/admin-emails?entity=suggestions&limit=240"), api("/api/admin-emails?entity=tasks&limit=240"), api("/api/admin-emails?entity=events&limit=240")]); dashboard = overview.dashboard || {}; data = { messages: messages.messages || [], suggestions: suggestions.suggestions || [], tasks: tasks.tasks || [], events: events.events || [] }; if (!currentItems().some((item) => item.id === selectedId)) selectedId = currentItems()[0]?.id || null; renderAll(); }
function renderAll() { renderKpis(); renderAssistant(); renderTabs(); renderList(); renderDetail(); }
function renderKpis() { if (!kpisEl) return; kpisEl.innerHTML = `<article><span>E-mails</span><strong>${dashboard?.total_messages || 0}</strong><small>${dashboard?.open_messages || 0} ouverts</small></article><article data-tone="warning"><span>A repondre</span><strong>${dashboard?.to_reply || 0}</strong><small>triage actif</small></article><article data-tone="danger"><span>Urgents</span><strong>${dashboard?.urgent || 0}</strong><small>P1</small></article><article><span>Suggestions</span><strong>${dashboard?.pending_suggestions || 0}</strong><small>a valider</small></article><article><span>Taches</span><strong>${dashboard?.open_tasks || 0}</strong><small>ouvertes</small></article>`; if (countEl) countEl.textContent = `${dashboard?.total_messages || 0} e-mail(s), ${dashboard?.to_reply || 0} a repondre, ${dashboard?.open_tasks || 0} tache(s).`; }
function renderAssistant() { const item = selectedItem(); const summary = view === "messages" ? item?.ai_summary : dashboard?.assistant?.summary; if (aiScoreEl) aiScoreEl.textContent = view === "messages" && item?.ai_confidence ? `${Math.round(item.ai_confidence * 100)}%` : `${dashboard?.pending_suggestions || 0}`; if (aiSummaryEl) aiSummaryEl.textContent = summary || dashboard?.assistant?.summary || "Analyse en attente."; if (!aiGridEl) return; const actions = view === "messages" && item ? [item.next_action, `Pole : ${item.pole}`, `Priorite : ${item.priority}`].filter(Boolean) : dashboard?.assistant?.priorities || []; aiGridEl.innerHTML = actions.length ? actions.slice(0, 4).map((action) => `<div><span>Action</span><strong>${escapeHtml(action)}</strong></div>`).join("") : `<div><span>Action</span><strong>Boite a jour</strong></div>`; }
function renderTabs() { tabs.forEach((button) => button.classList.toggle("is-active", button.dataset.emailsView === view)); }
function titleFor(item) { if (view === "messages") return item.subject || "E-mail"; if (view === "tasks") return item.title || "Tache"; if (view === "suggestions") return item.title || item.suggestion_type || "Suggestion"; return item.event_label || item.event_type || "Evenement"; }
function subFor(item) { if (view === "messages") return `${item.from_name || item.from_email || "Expediteur"} - ${item.pole || "Pole"}`; if (view === "tasks") return `${label(item.status)} - ${item.assigned_to || "A attribuer"}`; if (view === "suggestions") return `${item.suggestion_type || "IA"} - ${label(item.status)}`; return `${item.actor_label || "TVF OS"} - ${formatDate(item.created_at)}`; }
function itemStatus(item) { return item.status || item.priority || item.event_type || ""; }
function itemCard(item) { const tone = item.priority === "P1" || item.status === "new" ? " is-risk" : ""; return `<button class="admin-request emails-card${item.id === selectedId ? " is-active" : ""}${tone}" type="button" data-emails-id="${escapeHtml(item.id)}"><span class="admin-request-head"><strong>${escapeHtml(titleFor(item))}</strong><small>${escapeHtml(label(itemStatus(item)))}</small></span><span>${escapeHtml(subFor(item))}</span><span class="admin-request-sub">${escapeHtml(item.ai_summary || item.body_text || item.description || JSON.stringify(item.payload || {}).slice(0, 180))}</span><span class="admin-badges"><em>${escapeHtml(viewLabels[view])}</em><em>${escapeHtml(formatDate(item.received_at || item.due_at || item.created_at))}</em></span></button>`; }
function renderList() { if (listTitleEl) listTitleEl.textContent = viewLabels[view]; if (listCountEl) listCountEl.textContent = String(currentItems().length); if (emptyEl) emptyEl.hidden = currentItems().length > 0; if (listEl) listEl.innerHTML = currentItems().map(itemCard).join(""); }
function statusOptions(current) { const values = view === "messages" ? ["new", "analyzed", "to_reply", "waiting_info", "converted", "closed", "archive"] : view === "tasks" ? ["todo", "doing", "waiting", "done", "cancelled", "archive"] : ["proposed", "accepted", "modified", "rejected", "applied", "archive"]; return values.map((value) => `<option value="${value}" ${value === current ? "selected" : ""}>${escapeHtml(label(value))}</option>`).join(""); }
function renderDetail() { const item = selectedItem(); if (!detailEl) return; if (!item) { detailEl.innerHTML = `<p class="form-note">Aucun element selectionne.</p>`; return; } const readOnly = view === "events"; const type = view === "messages" ? "email" : view === "tasks" ? "task" : "suggestion"; const messageExtra = view === "messages" ? `<section class="emails-draft"><p class="section-kicker">Brouillon IA</p><textarea rows="8" data-email-draft>${escapeHtml(item.draft_response || "")}</textarea><div class="admin-detail-actions"><button class="btn secondary" type="button" data-copy-draft>Copier</button><button class="btn secondary" type="button" data-convert-email>Convertir en demande</button></div></section><pre>${escapeHtml(item.body_text || "")}</pre>` : ""; const form = readOnly ? `<pre>${escapeHtml(JSON.stringify(item, null, 2))}</pre>` : `<form class="emails-detail-form" data-emails-detail-form><input type="hidden" name="id" value="${escapeHtml(item.id)}"><input type="hidden" name="type" value="${escapeHtml(type)}">${view === "messages" ? `<label>Statut<select name="status">${statusOptions(item.status)}</select></label><label>Responsable<input name="assigned_to" value="${escapeHtml(item.assigned_to || "")}"></label><label>Pole<input name="pole" value="${escapeHtml(item.pole || "")}"></label><label>Prochaine action<input name="next_action" value="${escapeHtml(item.next_action || "")}"></label><label class="emails-wide-field">Pieces manquantes<textarea name="missing_pieces" rows="3">${escapeHtml((item.missing_pieces || []).join("\n"))}</textarea></label>` : view === "tasks" ? `<label>Statut<select name="status">${statusOptions(item.status)}</select></label><label>Responsable<input name="assigned_to" value="${escapeHtml(item.assigned_to || "")}"></label><label>Titre<input name="title" value="${escapeHtml(item.title || "")}"></label><label>Description<input name="description" value="${escapeHtml(item.description || "")}"></label>` : `<label>Statut<select name="status">${statusOptions(item.status)}</select></label><label>Relecteur<input name="reviewed_by" value="TVF OS"></label>`}<button class="btn primary" type="submit">Enregistrer</button></form>`; detailEl.innerHTML = `<div class="admin-panel-head"><div><p class="section-kicker">${escapeHtml(viewLabels[view])}</p><h2>${escapeHtml(titleFor(item))}</h2><p>${escapeHtml(subFor(item))}</p></div><span>${escapeHtml(label(itemStatus(item)))}</span></div>${form}${messageExtra}`; }
function openModal() { if (modal) modal.hidden = false; }
function closeModal() { if (modal) modal.hidden = true; modalForm?.reset(); }
function payloadFromForm(form) { const payload = Object.fromEntries(new FormData(form)); Object.keys(payload).forEach((key) => { payload[key] = String(payload[key] || "").trim(); if (!payload[key]) delete payload[key]; }); return payload; }
async function createEmail(event) { event.preventDefault(); await api("/api/admin-emails", { method: "POST", body: JSON.stringify({ type: "email", ...payloadFromForm(modalForm) }) }); closeModal(); await loadAll(); notify("E-mail ajoute au suivi.", "success"); }
async function saveDetail(form) { const payload = payloadFromForm(form); await api("/api/admin-emails", { method: "PATCH", body: JSON.stringify(payload) }); await loadAll(); notify("Element e-mail enregistre.", "success"); }
function exportCsv() { if (!currentItems().length) return notify("Aucun element a exporter.", "warning"); const rows = [["Vue", "Titre", "Statut", "Reference"], ...currentItems().map((item) => [viewLabels[view], titleFor(item), label(itemStatus(item)), subFor(item)])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `emails-tvf-os-${view}-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); notify("Export CSV prepare.", "success"); }
async function copyDraft(button) { const text = detailEl?.querySelector("[data-email-draft]")?.value || ""; if (!text.trim()) return notify("Aucun brouillon a copier.", "warning"); try { await navigator.clipboard.writeText(text); button.textContent = "Copie"; window.setTimeout(() => { button.textContent = "Copier"; }, 1400); notify("Brouillon copie.", "success"); } catch { notify("Copie automatique impossible. Selectionnez le brouillon manuellement.", "warning"); } }
async function convertEmail() { const item = selectedItem(); if (!item) return; await api("/api/admin-emails", { method: "POST", body: JSON.stringify({ type: "convert_request", id: item.id }) }); await loadAll(); notify("E-mail converti en demande.", "success"); }
function bindEvents() { tokenForm?.addEventListener("submit", async (event) => { event.preventDefault(); const value = String(new FormData(tokenForm).get("token") || "").trim(); if (!value) return setStatus("Entrez le token admin.", "error"); setToken(value); try { showApp(); await loadAll(); setStatus(""); } catch (error) { setToken(""); showLogin(); setStatus(error.status === 401 ? "Token admin invalide." : error.message, "error"); } }); filtersForm?.addEventListener("input", () => { clearTimeout(debounceTimer); debounceTimer = setTimeout(() => loadAll().catch((e) => notifyError(e)), 260); }); filtersForm?.addEventListener("change", () => loadAll().catch((e) => notifyError(e))); tabs.forEach((button) => button.addEventListener("click", () => { view = button.dataset.emailsView || "messages"; selectedId = currentItems()[0]?.id || null; renderAll(); })); refreshButton?.addEventListener("click", () => loadAll().catch((e) => notifyError(e))); createButton?.addEventListener("click", openModal); exportButton?.addEventListener("click", exportCsv); logoutButton?.addEventListener("click", () => { setToken(""); window.location.href = "admin"; }); closeModalButtons.forEach((button) => button.addEventListener("click", closeModal)); modal?.addEventListener("click", (event) => { if (event.target === modal) closeModal(); }); modalForm?.addEventListener("submit", createEmail); listEl?.addEventListener("click", (event) => { const button = event.target.closest("[data-emails-id]"); if (!button) return; selectedId = button.dataset.emailsId; renderAll(); }); detailEl?.addEventListener("submit", (event) => { const form = event.target.closest("[data-emails-detail-form]"); if (!form) return; event.preventDefault(); saveDetail(form).catch((e) => notifyError(e)); }); detailEl?.addEventListener("click", (event) => { const copy = event.target.closest("[data-copy-draft]"); if (copy) copyDraft(copy); if (event.target.closest("[data-convert-email]")) convertEmail().catch((e) => notifyError(e)); }); }
bindEvents();
if (token()) { showApp(); loadAll().catch((error) => { setToken(""); showLogin(); setStatus(error.status === 401 ? "Session expiree ou token invalide." : error.message, "error"); }); } else { showLogin(); }
