const WORK_TOKEN_KEY = "tvfAdminToken";
const labels = { todo: "A faire", doing: "En cours", waiting: "Attente", done: "Termine", cancelled: "Annule", archive: "Archive", active: "Actif", paused: "Pause", completed: "Termine", scheduled: "Planifie", confirmed: "Confirme", P1: "P1", P2: "P2", P3: "P3" };
const viewLabels = { tasks: "Taches", events: "Agenda", projects: "Projets", rules: "Automatisations" };
const loginSection = document.querySelector("[data-work-login]");
const appSection = document.querySelector("[data-work-app]");
const tokenForm = document.querySelector("[data-work-token-form]");
const loginStatus = document.querySelector("[data-work-login-status]");
const filtersForm = document.querySelector("[data-work-filters]");
const kpisEl = document.querySelector("[data-work-kpis]");
const listEl = document.querySelector("[data-work-list]");
const detailEl = document.querySelector("[data-work-detail]");
const countEl = document.querySelector("[data-work-count]");
const listCountEl = document.querySelector("[data-work-list-count]");
const listTitleEl = document.querySelector("[data-work-list-title]");
const emptyEl = document.querySelector("[data-work-empty]");
const aiScoreEl = document.querySelector("[data-work-ai-score]");
const aiSummaryEl = document.querySelector("[data-work-ai-summary]");
const aiGridEl = document.querySelector("[data-work-ai-grid]");
const tabs = document.querySelectorAll("[data-work-view]");
const createButton = document.querySelector("[data-work-create]");
const refreshButton = document.querySelector("[data-work-refresh]");
const exportButton = document.querySelector("[data-work-export]");
const logoutButton = document.querySelector("[data-work-logout]");
const modal = document.querySelector("[data-work-modal]");
const modalForm = document.querySelector("[data-work-form]");
const closeModalButtons = document.querySelectorAll("[data-work-close-modal]");
let view = "tasks";
let dashboard = null;
let data = { tasks: [], events: [], projects: [], rules: [] };
let selectedId = null;
let debounceTimer;
function token() { try { return sessionStorage.getItem(WORK_TOKEN_KEY) || ""; } catch { return ""; } }
function setToken(value) { try { if (value) sessionStorage.setItem(WORK_TOKEN_KEY, value); else sessionStorage.removeItem(WORK_TOKEN_KEY); } catch {} }
function showApp() { if (loginSection) loginSection.hidden = true; if (appSection) appSection.hidden = false; }
function showLogin() { if (loginSection) loginSection.hidden = false; if (appSection) appSection.hidden = true; }
function setStatus(message, type = "info") { if (!loginStatus) return; loginStatus.hidden = !message; loginStatus.textContent = message; loginStatus.dataset.status = type; }
function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function label(value) { return labels[value] || value || "Non renseigne"; }
function formatDate(value) { if (!value) return "Non renseigne"; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(date); }
function currentItems() { return data[view] || []; }
function selectedItem() { return currentItems().find((item) => item.id === selectedId) || currentItems()[0] || null; }
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const text = await response.text(); const result = text ? JSON.parse(text) : { ok: response.ok }; if (!response.ok || result.ok === false) { const error = new Error(result.error || "Action impossible."); error.status = response.status; throw error; } return result; }
function filtersParams(entity) { const formData = new FormData(filtersForm); const params = new URLSearchParams({ entity, limit: "260" }); const q = String(formData.get("q") || "").trim(); const status = String(formData.get("status") || "").trim(); if (q) params.set("q", q); if (status && status !== "all") params.set("status", status); return params; }
async function loadAll() { if (countEl) countEl.textContent = "Chargement du planning..."; const overview = await api("/api/admin-work?entity=dashboard"); const [tasks, events, projects, rules] = await Promise.all([api(`/api/admin-work?${filtersParams("tasks").toString()}`), api(`/api/admin-work?${filtersParams("events").toString()}`), api(`/api/admin-work?${filtersParams("projects").toString()}`), api("/api/admin-work?entity=rules&limit=200")]); dashboard = overview.dashboard || {}; data = { tasks: tasks.tasks || [], events: events.events || [], projects: projects.projects || [], rules: rules.rules || [] }; if (!currentItems().some((item) => item.id === selectedId)) selectedId = currentItems()[0]?.id || null; renderAll(); }
function renderAll() { renderKpis(); renderAssistant(); renderTabs(); renderList(); renderDetail(); }
function renderKpis() { if (!kpisEl) return; kpisEl.innerHTML = `<article><span>Projets actifs</span><strong>${dashboard?.active_projects || 0}</strong><small>en cours</small></article><article><span>Taches ouvertes</span><strong>${dashboard?.open_tasks || 0}</strong><small>a suivre</small></article><article data-tone="danger"><span>Retards</span><strong>${dashboard?.overdue_tasks || 0}</strong><small>a traiter</small></article><article><span>Aujourd'hui</span><strong>${dashboard?.today_events || 0}</strong><small>agenda</small></article><article><span>Regles</span><strong>${dashboard?.active_rules || 0}</strong><small>actives</small></article>`; if (countEl) countEl.textContent = `${dashboard?.open_tasks || 0} tache(s), ${dashboard?.overdue_tasks || 0} retard(s), ${dashboard?.today_events || 0} evenement(s) aujourd'hui.`; }
function renderAssistant() { const item = selectedItem(); const assistant = item?.assistant || dashboard?.assistant || {}; if (aiScoreEl) aiScoreEl.textContent = item?.assistant?.urgency_score ? `${item.assistant.urgency_score}%` : `${dashboard?.overdue_tasks || 0}`; if (aiSummaryEl) aiSummaryEl.textContent = assistant.summary || dashboard?.assistant?.summary || "Analyse en attente."; if (!aiGridEl) return; const actions = assistant.next_actions || dashboard?.assistant?.priorities || []; aiGridEl.innerHTML = actions.length ? actions.slice(0, 4).map((action) => `<div><span>Action</span><strong>${escapeHtml(action)}</strong></div>`).join("") : `<div><span>Action</span><strong>Planning sous controle</strong></div>`; }
function renderTabs() { tabs.forEach((button) => button.classList.toggle("is-active", button.dataset.workView === view)); }
function titleFor(item) { return item.title || item.rule_key || "Element"; }
function subFor(item) { return item.assigned_to || item.owner_name || item.organizer_name || item.pole || item.trigger_type || "TVF OS"; }
function itemStatus(item) { return item.status || item.priority || ""; }
function itemDate(item) { return item.due_at || item.starts_at || item.updated_at || item.created_at; }
function itemCard(item) { const risk = item.assistant?.overdue || item.priority === "P1" ? " is-risk" : ""; return `<button class="admin-request work-card${item.id === selectedId ? " is-active" : ""}${risk}" type="button" data-work-id="${escapeHtml(item.id)}"><span class="admin-request-head"><strong>${escapeHtml(titleFor(item))}</strong><small>${escapeHtml(label(itemStatus(item)))}</small></span><span>${escapeHtml(subFor(item))}</span><span class="admin-request-sub">${escapeHtml(item.description || item.summary || item.notes || item.ai_summary || "")}</span><span class="admin-badges"><em>${escapeHtml(viewLabels[view])}</em><em>${escapeHtml(formatDate(itemDate(item)))}</em></span></button>`; }
function renderList() { if (listTitleEl) listTitleEl.textContent = viewLabels[view]; if (listCountEl) listCountEl.textContent = String(currentItems().length); if (emptyEl) emptyEl.hidden = currentItems().length > 0; if (listEl) listEl.innerHTML = currentItems().map(itemCard).join(""); }
function statusOptions(current) { const values = view === "tasks" ? ["todo", "doing", "waiting", "done", "cancelled", "archive"] : view === "events" ? ["scheduled", "confirmed", "done", "cancelled", "archive"] : ["draft", "active", "paused", "completed", "cancelled", "archive"]; return values.map((value) => `<option value="${value}" ${value === current ? "selected" : ""}>${escapeHtml(label(value))}</option>`).join(""); }
function renderDetail() { const item = selectedItem(); if (!detailEl) return; if (!item) { detailEl.innerHTML = `<p class="form-note">Aucun element selectionne.</p>`; return; } const type = view === "projects" ? "project" : view === "events" ? "event" : "task"; const editable = view !== "rules"; const form = editable ? `<form class="work-detail-form" data-work-detail-form><input type="hidden" name="id" value="${escapeHtml(item.id)}"><input type="hidden" name="type" value="${escapeHtml(type)}"><label>Titre<input name="title" value="${escapeHtml(item.title || "")}"></label><label>Statut<select name="status">${statusOptions(item.status)}</select></label><label>Responsable<input name="assigned_to" value="${escapeHtml(item.assigned_to || item.owner_name || item.organizer_name || "")}"></label><label>Pole<input name="pole" value="${escapeHtml(item.pole || "")}"></label><label class="work-wide-field">Description<textarea name="summary" rows="5">${escapeHtml(item.description || item.summary || item.notes || "")}</textarea></label><button class="btn primary" type="submit">Enregistrer</button></form>` : `<pre>${escapeHtml(JSON.stringify(item, null, 2))}</pre>`; detailEl.innerHTML = `<div class="admin-panel-head"><div><p class="section-kicker">${escapeHtml(viewLabels[view])}</p><h2>${escapeHtml(titleFor(item))}</h2><p>${escapeHtml(subFor(item))}</p></div><span>${escapeHtml(label(itemStatus(item)))}</span></div>${form}`; }
function openModal() { if (modal) modal.hidden = false; }
function closeModal() { if (modal) modal.hidden = true; modalForm?.reset(); }
function payloadFromForm(form) { const payload = Object.fromEntries(new FormData(form)); Object.keys(payload).forEach((key) => { payload[key] = String(payload[key] || "").trim(); if (!payload[key]) delete payload[key]; }); if (payload.type === "event") { payload.starts_at = payload.due_at; delete payload.due_at; } if (payload.summary) payload.description = payload.summary; return payload; }
async function createItem(event) { event.preventDefault(); await api("/api/admin-work", { method: "POST", body: JSON.stringify(payloadFromForm(modalForm)) }); closeModal(); await loadAll(); }
async function saveDetail(form) { const payload = payloadFromForm(form); await api("/api/admin-work", { method: "PATCH", body: JSON.stringify(payload) }); await loadAll(); }
function exportCsv() { const rows = [["Vue", "Titre", "Statut", "Responsable", "Date"], ...currentItems().map((item) => [viewLabels[view], titleFor(item), label(itemStatus(item)), subFor(item), formatDate(itemDate(item))])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `planning-tvf-os-${view}-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); }
function bindEvents() { tokenForm?.addEventListener("submit", async (event) => { event.preventDefault(); const value = String(new FormData(tokenForm).get("token") || "").trim(); if (!value) return setStatus("Entrez le token admin.", "error"); setToken(value); try { showApp(); await loadAll(); setStatus(""); } catch (error) { setToken(""); showLogin(); setStatus(error.status === 401 ? "Token admin invalide." : error.message, "error"); } }); filtersForm?.addEventListener("input", () => { clearTimeout(debounceTimer); debounceTimer = setTimeout(() => loadAll().catch((e) => alert(e.message)), 260); }); filtersForm?.addEventListener("change", () => loadAll().catch((e) => alert(e.message))); tabs.forEach((button) => button.addEventListener("click", () => { view = button.dataset.workView || "tasks"; selectedId = currentItems()[0]?.id || null; renderAll(); })); refreshButton?.addEventListener("click", () => loadAll().catch((e) => alert(e.message))); createButton?.addEventListener("click", openModal); exportButton?.addEventListener("click", exportCsv); logoutButton?.addEventListener("click", () => { setToken(""); window.location.href = "admin"; }); closeModalButtons.forEach((button) => button.addEventListener("click", closeModal)); modal?.addEventListener("click", (event) => { if (event.target === modal) closeModal(); }); modalForm?.addEventListener("submit", createItem); listEl?.addEventListener("click", (event) => { const button = event.target.closest("[data-work-id]"); if (!button) return; selectedId = button.dataset.workId; renderAll(); }); detailEl?.addEventListener("submit", (event) => { const form = event.target.closest("[data-work-detail-form]"); if (!form) return; event.preventDefault(); saveDetail(form).catch((e) => alert(e.message)); }); }
bindEvents();
if (token()) { showApp(); loadAll().catch((error) => { setToken(""); showLogin(); setStatus(error.status === 401 ? "Session expiree ou token invalide." : error.message, "error"); }); } else { showLogin(); }
