const AI_TOKEN_KEY = "tvfAdminToken";
const suggestionStatusLabels = { proposed: "A valider", accepted: "Acceptee", modified: "Modifiee", rejected: "Refusee", ignored: "Ignoree", applied: "Appliquee" };
const suggestionTypeLabels = { classification: "Classification", priority: "Priorite", pole: "Pole", responsible: "Responsable", next_action: "Prochaine action", draft_response: "Brouillon", missing_pieces: "Pieces manquantes", checklist: "Checklist", procedure: "Procedure", risk: "Risque", knowledge: "Connaissance", email_triage: "Tri e-mail", other: "Autre" };

const loginSection = document.querySelector("[data-ai-login]");
const appSection = document.querySelector("[data-ai-app]");
const tokenForm = document.querySelector("[data-ai-token-form]");
const loginStatus = document.querySelector("[data-ai-login-status]");
const kpisEl = document.querySelector("[data-ai-kpis]");
const countEl = document.querySelector("[data-ai-count]");
const refreshButton = document.querySelector("[data-ai-refresh]");
const logoutButton = document.querySelector("[data-ai-logout]");
const exportButton = document.querySelector("[data-ai-export]");
const viewButtons = document.querySelectorAll("[data-ai-view]");
const panels = document.querySelectorAll("[data-ai-panel]");
const questionForm = document.querySelector("[data-ai-question-form]");
const emailForm = document.querySelector("[data-ai-email-form]");
const answerEl = document.querySelector("[data-ai-answer]");
const emailAnswerEl = document.querySelector("[data-ai-email-answer]");
const suggestionsEl = document.querySelector("[data-ai-suggestions]");
const suggestionDetailEl = document.querySelector("[data-ai-suggestion-detail]");
const suggestionsEmpty = document.querySelector("[data-ai-suggestions-empty]");
const suggestionFilters = document.querySelector("[data-ai-suggestion-filters]");
const historyEl = document.querySelector("[data-ai-history]");
const automationsEl = document.querySelector("[data-ai-automations]");
const sourcesEl = document.querySelector("[data-ai-sources]");

let dashboard = null;
let suggestions = [];
let interactions = [];
let automations = { rules: [], runs: [] };
let sources = {};
let selectedSuggestionId = null;
let view = "conversation";

function token() { try { return sessionStorage.getItem(AI_TOKEN_KEY) || ""; } catch { return ""; } }
function setToken(value) { try { if (value) sessionStorage.setItem(AI_TOKEN_KEY, value); else sessionStorage.removeItem(AI_TOKEN_KEY); } catch {} }
function showApp() { if (loginSection) loginSection.hidden = true; if (appSection) appSection.hidden = false; }
function showLogin() { if (loginSection) loginSection.hidden = false; if (appSection) appSection.hidden = true; }
function setStatus(message, type = "info") { if (!loginStatus) return; loginStatus.hidden = !message; loginStatus.textContent = message; loginStatus.dataset.status = type; }
function notify(message, type = "info") { if (window.tvfAdminNotice) window.tvfAdminNotice(message, type); else if (type === "error") console.error(message); else console.log(message); }
function notifyError(error, fallback = "Action impossible pour le moment.") { notify(error?.message || fallback, "error"); }
function escapeHtml(value) { return String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;"); }
function formatDate(value) { if (!value) return "Non renseigne"; const date = new Date(value); if (Number.isNaN(date.getTime())) return value; return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short" }).format(date); }
function label(map, value) { return map[value] || value || "Non renseigne"; }
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const text = await response.text(); const result = text ? JSON.parse(text) : { ok: response.ok }; if (!response.ok || result.ok === false) throw new Error(result.error || "Action impossible."); return result; }
function switchView(next) { view = next; viewButtons.forEach((button) => button.classList.toggle("is-active", button.dataset.aiView === view)); panels.forEach((panel) => { panel.hidden = panel.dataset.aiPanel !== view; }); if (view === "suggestions") loadSuggestions().catch((e) => notifyError(e)); if (view === "history") loadHistory().catch((e) => notifyError(e)); if (view === "automations") loadAutomations().catch((e) => notifyError(e)); if (view === "sources") loadSources().catch((e) => notifyError(e)); }
function renderKpis() { if (!kpisEl || !dashboard) return; kpisEl.innerHTML = `<article><span>Interactions</span><strong>${dashboard.interactions_total || 0}</strong><small>Journal</small></article><article data-tone="warning"><span>A valider</span><strong>${dashboard.suggestions_pending || 0}</strong><small>Suggestions</small></article><article data-tone="info"><span>Acceptation</span><strong>${dashboard.acceptance_rate || 0}%</strong><small>Humain</small></article><article><span>Sources</span><strong>${(dashboard.sources?.knowledge || 0) + (dashboard.sources?.procedures || 0) + (dashboard.sources?.documents || 0) + (dashboard.sources?.cases || 0)}</strong><small>Disponibles</small></article><article data-tone="danger"><span>A revoir</span><strong>${dashboard.needs_review || 0}</strong><small>Confiance basse</small></article>`; }
async function loadDashboard() { const result = await api("/api/admin-ai?entity=dashboard"); dashboard = result.dashboard || {}; if (countEl) countEl.textContent = `${dashboard.suggestions_pending || 0} suggestion(s) a valider, ${dashboard.interactions_total || 0} interaction(s) journalisee(s).`; renderKpis(); }
function answerHtml(response, interaction) { const missing = response.missing_information || []; const sourcesList = response.sources || []; return `<div class="admin-panel-head"><div><p class="section-kicker">Reponse IA</p><h3>Proposition a valider</h3></div><strong>${Math.round((response.confidence || 0) * 100)}%</strong></div><p>${escapeHtml(response.answer_text || response.recommendation || "Reponse indisponible.")}</p><div class="admin-ai-grid"><div><span>Categorie</span><strong>${escapeHtml(response.suggested_category || "-")}</strong></div><div><span>Pole</span><strong>${escapeHtml(response.suggested_pole || "-")}</strong></div><div><span>Priorite</span><strong>${escapeHtml(response.suggested_priority || "-")}</strong></div><div><span>Trace</span><strong>${escapeHtml(interaction?.id ? "Journalisee" : "Non journalisee")}</strong></div></div><section class="knowledge-panel"><p class="section-kicker">Actions proposees</p><ul>${(response.next_actions || []).map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul></section><section class="knowledge-panel"><p class="section-kicker">Informations manquantes</p>${missing.length ? `<ul>${missing.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>` : "<p>Aucune information manquante detectee.</p>"}</section><section class="knowledge-panel"><p class="section-kicker">Sources</p>${sourcesList.length ? sourcesList.map((s) => `<article><strong>${escapeHtml(s)}</strong></article>`).join("") : "<p>Aucune source interne suffisante. Validation renforcee requise.</p>"}</section>`; }
async function askQuestion(event) { event.preventDefault(); if (!answerEl) return; const data = Object.fromEntries(new FormData(questionForm)); answerEl.hidden = false; answerEl.innerHTML = "<p>Analyse en cours...</p>"; try { const result = await api("/api/admin-ai", { method: "POST", body: JSON.stringify({ type: "ask", ...data }) }); answerEl.innerHTML = answerHtml(result.response || {}, result.interaction); questionForm.reset(); await loadDashboard().catch(() => {}); } catch (error) { answerEl.innerHTML = `<p>${escapeHtml(error.message)}</p>`; } }
async function analyzeEmail(event) { event.preventDefault(); if (!emailAnswerEl) return; const data = Object.fromEntries(new FormData(emailForm)); emailAnswerEl.hidden = false; emailAnswerEl.innerHTML = "<p>Lecture de l'e-mail...</p>"; try { const result = await api("/api/admin-ai", { method: "POST", body: JSON.stringify({ type: "email_analysis", ...data }) }); emailAnswerEl.innerHTML = answerHtml(result.response || {}, result.interaction) + `<section class="knowledge-panel"><p class="section-kicker">Suggestion creee</p><p>${escapeHtml(result.suggestion?.title || "Tri e-mail")}</p><div class="admin-detail-actions"><button class="btn secondary" type="button" data-open-suggestions>Voir les suggestions</button></div></section>`; emailForm.reset(); await loadDashboard().catch(() => {}); } catch (error) { emailAnswerEl.innerHTML = `<p>${escapeHtml(error.message)}</p>`; } }
function suggestionCard(item) { return `<button class="admin-request ai-suggestion-card${item.id === selectedSuggestionId ? " is-active" : ""}" type="button" data-suggestion-id="${escapeHtml(item.id)}"><span class="admin-request-head"><strong>${escapeHtml(label(suggestionTypeLabels, item.suggestion_type))}</strong><small>${escapeHtml(label(suggestionStatusLabels, item.status))}</small></span><span>${escapeHtml(item.title || "Suggestion IA")}</span><span class="admin-request-sub">${escapeHtml(item.explanation || "A valider par un humain.")}</span><span class="admin-badges"><em data-kind="priority">${Math.round((item.confidence || 0) * 100)}%</em><em data-kind="category">${escapeHtml(item.related_object_type || "none")}</em><em data-kind="status">${(item.sources || []).length} sources</em></span></button>`; }
function renderSuggestions() { if (!suggestionsEl) return; suggestionsEl.innerHTML = suggestions.map(suggestionCard).join(""); if (suggestionsEmpty) suggestionsEmpty.hidden = suggestions.length !== 0; if (!selectedSuggestionId || !suggestions.some((s) => s.id === selectedSuggestionId)) selectedSuggestionId = suggestions[0]?.id || null; renderSuggestionDetail(); }
function renderSuggestionDetail() { if (!suggestionDetailEl) return; const item = suggestions.find((s) => s.id === selectedSuggestionId); if (!item) { suggestionDetailEl.innerHTML = `<div class="admin-detail-empty"><p class="section-kicker">Detail</p><h3>Selectionnez une suggestion</h3><p>Chaque proposition importante doit etre acceptee, modifiee ou refusee.</p></div>`; return; } const proposed = item.proposed_value || {}; suggestionDetailEl.innerHTML = `<div class="admin-detail-form ai-detail-form"><div class="admin-detail-title"><p class="section-kicker">${escapeHtml(label(suggestionTypeLabels, item.suggestion_type))}</p><h3>${escapeHtml(item.title || "Suggestion IA")}</h3><p>${escapeHtml(label(suggestionStatusLabels, item.status))} - confiance ${Math.round((item.confidence || 0) * 100)}%</p></div><div class="admin-meta-grid"><div><span>Objet</span><strong>${escapeHtml(item.related_object_type || "none")}</strong></div><div><span>Creation</span><strong>${escapeHtml(formatDate(item.created_at))}</strong></div><div><span>Revue</span><strong>${escapeHtml(formatDate(item.reviewed_at))}</strong></div><div><span>Sources</span><strong>${escapeHtml(String((item.sources || []).length))}</strong></div></div><section class="knowledge-panel"><p class="section-kicker">Explication</p><p>${escapeHtml(item.explanation || "Suggestion a controler.")}</p></section><section class="knowledge-panel"><p class="section-kicker">Valeur proposee</p><pre>${escapeHtml(JSON.stringify(proposed, null, 2))}</pre></section><section class="knowledge-panel"><p class="section-kicker">Sources</p>${(item.sources || []).length ? item.sources.map((s) => `<article><strong>${escapeHtml(s)}</strong></article>`).join("") : "<p>Aucune source citee.</p>"}</section><div class="admin-detail-actions"><button class="btn primary" type="button" data-suggestion-action="accepted">Accepter</button><button class="btn secondary" type="button" data-suggestion-action="applied">Marquer appliquee</button><button class="btn ghost" type="button" data-suggestion-action="rejected">Refuser</button><button class="btn ghost" type="button" data-suggestion-action="ignored">Ignorer</button></div></div>`; }
function suggestionParams() { const data = new FormData(suggestionFilters); const params = new URLSearchParams({ entity: "suggestions", limit: "100" }); ["status", "suggestion_type"].forEach((key) => { const value = String(data.get(key) || "").trim(); if (value) params.set(key, value); }); return params; }
async function loadSuggestions() { const result = await api(`/api/admin-ai?${suggestionParams().toString()}`); suggestions = result.suggestions || []; renderSuggestions(); }
async function reviewSuggestion(status) { const item = suggestions.find((s) => s.id === selectedSuggestionId); if (!item) return; const body = { type: "suggestion", id: item.id, status, reviewed_by: "TVF OS" }; if (status === "rejected") body.rejected_reason = "Refuse par TVF OS apres revue humaine."; const result = await api("/api/admin-ai", { method: "PATCH", body: JSON.stringify(body) }); suggestions = suggestions.map((s) => s.id === item.id ? result.suggestion : s); renderSuggestions(); await loadDashboard().catch(() => {}); notify("Suggestion IA mise a jour.", "success"); }
async function loadHistory() { const result = await api("/api/admin-ai?entity=interactions&limit=80"); interactions = result.interactions || []; if (!historyEl) return; historyEl.innerHTML = interactions.length ? interactions.map((item) => `<article class="ai-history-item"><strong>${escapeHtml(item.prompt_summary || item.interaction_type)}</strong><span>${escapeHtml(item.interaction_type)} - ${escapeHtml(formatDate(item.created_at))} - ${Math.round((item.confidence || 0) * 100)}%</span><p>${escapeHtml(item.response_summary || "")}</p></article>`).join("") : "<p>Aucune interaction journalisee.</p>"; }
async function loadAutomations() { const result = await api("/api/admin-ai?entity=automations"); automations = result.automations || { rules: [], runs: [] }; if (!automationsEl) return; const rules = automations.rules || []; const runs = automations.runs || []; automationsEl.innerHTML = `<div class="ai-source-grid"><article><span>Regles</span><strong>${rules.length}</strong></article><article><span>Executions</span><strong>${runs.length}</strong></article></div>${rules.length ? rules.map((rule) => `<article class="ai-history-item"><strong>${escapeHtml(rule.rule_name)}</strong><span>${escapeHtml(rule.trigger_type)} - ${rule.enabled ? "Active" : "Inactive"}</span><p>${escapeHtml(rule.description || "")}</p></article>`).join("") : "<p>Aucune regle IA preparee.</p>"}`; }
async function loadSources() { const result = await api("/api/admin-ai?entity=sources"); sources = result.sources || {}; if (!sourcesEl) return; sourcesEl.innerHTML = Object.entries(sources).map(([key, value]) => `<article><span>${escapeHtml(key)}</span><strong>${escapeHtml(String(value))}</strong></article>`).join(""); }
function exportCsv() { const rows = suggestions.map((item) => [item.title, label(suggestionTypeLabels, item.suggestion_type), label(suggestionStatusLabels, item.status), item.confidence, (item.sources || []).join(", ")]); const csv = [["Titre", "Type", "Statut", "Confiance", "Sources"], ...rows].map((row) => row.map((v) => `"${String(v || "").replace(/"/g, '""')}"`).join(";")).join("\n"); const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `suggestions-ia-tvf-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); notify("Export IA prepare.", "success"); }
function bindEvents() { tokenForm?.addEventListener("submit", async (event) => { event.preventDefault(); const value = String(new FormData(tokenForm).get("token") || "").trim(); if (!value) return setStatus("Entrez le token admin.", "error"); setToken(value); try { showApp(); await loadDashboard(); setStatus(""); } catch (error) { setToken(""); showLogin(); setStatus(error.message, "error"); } }); viewButtons.forEach((button) => button.addEventListener("click", () => switchView(button.dataset.aiView || "conversation"))); refreshButton?.addEventListener("click", () => Promise.all([loadDashboard(), view === "suggestions" ? loadSuggestions() : Promise.resolve(), view === "history" ? loadHistory() : Promise.resolve(), view === "automations" ? loadAutomations() : Promise.resolve(), view === "sources" ? loadSources() : Promise.resolve()]).catch((e) => notifyError(e))); logoutButton?.addEventListener("click", () => { setToken(""); window.location.href = "admin-login"; }); exportButton?.addEventListener("click", exportCsv); questionForm?.addEventListener("submit", askQuestion); emailForm?.addEventListener("submit", analyzeEmail); suggestionFilters?.addEventListener("change", () => loadSuggestions().catch((e) => notifyError(e))); suggestionsEl?.addEventListener("click", (event) => { const button = event.target.closest("[data-suggestion-id]"); if (!button) return; selectedSuggestionId = button.dataset.suggestionId; renderSuggestions(); }); suggestionDetailEl?.addEventListener("click", (event) => { const action = event.target.closest("[data-suggestion-action]"); if (action) reviewSuggestion(action.dataset.suggestionAction).catch((e) => notifyError(e)); }); document.addEventListener("click", (event) => { if (event.target.closest("[data-open-suggestions]")) switchView("suggestions"); }); }
bindEvents();
if (token()) { showApp(); loadDashboard().catch((error) => { setToken(""); showLogin(); setStatus(error.message, "error"); }); } else { showLogin(); }
