from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
ROOT=Path(r'C:\Users\jowst\Documents\TERRITOIRES VIVANTS FRANCE')
PDF=ROOT/'documents'/'brochures-tvf'/'catalogue-conventions-cadres-tvf.pdf'
LOGO=ROOT/'assets'/'logo-territoires-vivants-france-web.png'
TVF={'name':'Territoires Vivants France','subtitle':'Agence Territoriale de Revitalisation Immobilière','address':'25 rue Élise Gervais, 42000 Saint-Étienne','phone':'04 65 81 54 69','email':'contact@territoiresvivantsfrance.fr','rna':'RNA W922015538','siret':'SIRET 897 226 138 00018'}
DETAILS=[
('Convention cadre propriétaire','Socle de relation avec le propriétaire. Elle permet d’étudier le bien, organiser la visite, recevoir les documents et présenter des pistes sans transfert de droit sur le bien.',['Le propriétaire reste propriétaire et décide des suites.','TVF accompagne, oriente et coordonne sans devenir gestionnaire.','Les clauses visite, photos, documents, confidentialité et absence de mandat immobilier doivent être intégrées.','Toute proposition de valorisation reste soumise à vérification et accord écrit.'],['Promettre rendement, aide, locataire, vente ou travaux.','Entrer dans un bien sans autorisation.']),
('Convention de mise à disposition d’un bien','À utiliser lorsqu’un usage réel du bien est accordé : stockage, projet associatif, occupation temporaire, atelier ou expérimentation.',['Décrire usage, durée, bénéficiaire, accès, horaires et zones autorisées.','Préciser charges, fluides, entretien, assurances, sécurité et restitution.','Qualifier juridiquement toute participation financière, indemnité, redevance ou rendement.','Prévoir état des lieux d’entrée et de sortie.'],['Créer un bail déguisé sans analyse.','Promettre un rendement non encadré.']),
('Convention cadre collectivité','Cadre de coopération avec commune, intercommunalité, département ou établissement public.',['TVF appuie repérage, observatoire, qualification et suivi.','La collectivité conserve ses compétences et décisions.','Les données doivent être partagées selon finalité, sécurité, confidentialité et accès limité.','Les restitutions publiques doivent être vérifiées, anonymisées ou agrégées.'],['Présenter TVF comme autorité publique.','Qualifier juridiquement un bien sur simple signalement.']),
('Convention cadre entreprise / partenaire','Cadre pour expertise, mécénat, prestation, parrainage, action commune ou soutien territorial.',['Distinguer don, mécénat, prestation et partenariat opérationnel.','Préciser livrables, responsabilités, assurances et coûts éventuels.','Valider toute communication et usage de logo.','Vérifier la nature fiscale ou commerciale de la contribution.'],['Confondre mécénat et sponsoring.','Annoncer une réduction fiscale automatique.']),
('Convention ressources et matériaux','Cadre pour dons, collecte, stockage, contrôle, réemploi et affectation de matériaux ou équipements.',['Inventorier quantité, état, origine, lieu, photos et valeur estimative si connue.','Définir transport, manutention, stockage, responsabilité et assurance.','Prévoir droit de refus TVF en cas de risque, non-conformité ou absence d’utilité.','Tracer entrée, sortie et affectation projet.'],['Distribuer sans cadre.','Délivrer un reçu fiscal non vérifié.']),
('Convention projet solidaire / association','Cadre pour insertion, formation, ateliers, actions solidaires, réemploi ou activation locale.',['Décrire objectifs, public, lieu, calendrier et encadrement.','Vérifier assurances, sécurité, outillage, accueil du public et autorisations.','Prévoir mise à disposition séparée si un bien est utilisé.','Organiser bilan, photos autorisées et retour d’expérience.'],['Confondre appui TVF et responsabilité totale sur les participants.','Organiser un chantier sans encadrement compétent.']),
('Convention confidentialité et données','Clause autonome ou annexe pour toute information sensible : propriétaires, adresses, photos, documents, devis, dossiers, accès TVF OS.',['Définir finalité, personnes habilitées et durée de conservation.','Limiter les données à ce qui est nécessaire.','Prévoir sécurité, restitution, suppression et procédure incident.','Interdire réutilisation ou diffusion sans accord.'],['Transmettre données ou photos sans nécessité.','Utiliser les informations pour une autre finalité.'])]
UNIVERSAL=[('Objet et périmètre','Définir ce qui est couvert et ce qui ne l’est pas.'),('Capacité du signataire','Vérifier que la personne peut engager le propriétaire ou l’organisation.'),('Absence de mandat immobilier','Éviter toute confusion avec vente, location, gestion ou entremise réglementée.'),('Visite et photos','Autorisation, sécurité, usage interne, diffusion seulement avec accord.'),('Rendement ou participation','À qualifier juridiquement avant toute promesse.'),('Matériaux','Inventaire, contrôle, stockage, transport, affectation, traçabilité.'),('Fiscalité','Aucun avantage fiscal automatique.'),('RGPD','Finalité, minimisation, transparence, droits, durée, sécurité.'),('Restitution','Fin de convention, remise du bien, données, matériaux ou accès.')]
st=getSampleStyleSheet(); st.add(ParagraphStyle(name='T',fontName='Helvetica-Bold',fontSize=21,leading=25,textColor=colors.HexColor('#18392F'),alignment=1)); st.add(ParagraphStyle(name='Sub',fontSize=10.5,leading=14,textColor=colors.HexColor('#667085'),alignment=1,spaceAfter=8)); st.add(ParagraphStyle(name='H1',fontName='Helvetica-Bold',fontSize=16,leading=20,textColor=colors.HexColor('#18392F'),spaceBefore=8,spaceAfter=6)); st.add(ParagraphStyle(name='H2',fontName='Helvetica-Bold',fontSize=11,leading=14,textColor=colors.HexColor('#18392F'),spaceBefore=5,spaceAfter=3)); st.add(ParagraphStyle(name='B',fontSize=9.6,leading=13,textColor=colors.HexColor('#1F2937'),spaceAfter=5)); st.add(ParagraphStyle(name='Small',fontSize=7.7,leading=9.6,textColor=colors.HexColor('#667085'))); st.add(ParagraphStyle(name='Note',fontSize=8.4,leading=11,textColor=colors.HexColor('#475467'),backColor=colors.HexColor('#FBF8EF'),borderColor=colors.HexColor('#E4D7B8'),borderWidth=.5,borderPadding=7,spaceAfter=8))
story=[]
if LOGO.exists(): story.append(Image(str(LOGO),width=35*mm,height=26*mm))
story.append(Spacer(1,10*mm)); story.append(Paragraph('CATALOGUE DES CONVENTIONS CADRES TVF',st['T'])); story.append(Paragraph('Guide interne d’utilisation, clauses universelles et règles de prudence',st['Sub'])); story.append(Paragraph('Brochure de doctrine interne destinée à comprendre les grandes conventions TVF, leurs usages, leurs clauses centrales et les précautions à respecter pour les propriétaires, collectivités, entreprises, associations et partenaires.',st['Note'])); story.append(Paragraph(f"<b>{TVF['name']}</b><br/>{TVF['subtitle']}<br/>{TVF['address']} | {TVF['phone']} | {TVF['email']}<br/>{TVF['rna']} | {TVF['siret']}",st['Small'])); story.append(PageBreak())
story.append(Paragraph('Architecture des conventions TVF',st['H1'])); story.append(Paragraph('TVF doit fonctionner avec peu de grandes conventions cadres. Les autorisations secondaires deviennent des clauses ou annexes : visite, photos, documents, état des lieux, inventaire matériaux, confidentialité, restitution ou classement sans suite.',st['B'])); story.append(Paragraph('Cette méthode évite de multiplier les documents et donne une logique professionnelle : une convention principale, des articles universels, des annexes adaptées au cas concret.',st['B'])); story.append(PageBreak())
for title,intro,clauses,avoids in DETAILS:
    story.append(Paragraph(title,st['H1'])); story.append(Paragraph(intro,st['B'])); story.append(Paragraph('Clauses et règles à prévoir',st['H2']))
    for c in clauses: story.append(Paragraph('• '+c,st['B']))
    story.append(Paragraph('Points à éviter',st['H2']))
    for a in avoids: story.append(Paragraph('• '+a,st['B']))
    story.append(Paragraph('Usage recommandé. Cette convention doit être adaptée au dossier, complétée par les annexes nécessaires et relue juridiquement avant signature réelle.',st['Note'])); story.append(PageBreak())
story.append(Paragraph('Articles universels à intégrer',st['H1']))
rows=[[Paragraph('Article',st['Small']),Paragraph('Utilité',st['Small'])]]+[[Paragraph(a,st['Small']),Paragraph(b,st['Small'])] for a,b in UNIVERSAL]
t=Table(rows,colWidths=[52*mm,117*mm],repeatRows=1); t.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.35,colors.HexColor('#D9E0DC')),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#F3F7F2')),('VALIGN',(0,0),(-1,-1),'TOP'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); story.append(t); story.append(Spacer(1,5*mm)); story.append(Paragraph('Références de prudence',st['H1']))
for ref in ['Service-Public Entreprendre : mécénat d’entreprise, formes de dons et conditions de réduction d’impôt.', 'Impots.gouv.fr : règles fiscales relatives aux dons et réductions d’impôt.', 'CNIL : principes RGPD de finalité, minimisation, transparence, droits des personnes, durée de conservation et sécurité.', 'Service-Public : prudence sur les activités immobilières réglementées et le cadre professionnel adapté.']:
    story.append(Paragraph('• '+ref,st['Small']))
story.append(Paragraph('Ce catalogue reste un outil interne. Il ne remplace pas une consultation juridique et ne doit pas être utilisé comme convention définitive sans adaptation au cas concret.',st['Note']))
SimpleDocTemplate(str(PDF),pagesize=A4,rightMargin=14*mm,leftMargin=14*mm,topMargin=13*mm,bottomMargin=13*mm).build(story)
print(PDF)
