from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image

ROOT = Path(r'C:\Users\jowst\Documents\TERRITOIRES VIVANTS FRANCE')
OUT = ROOT / 'documents' / 'conventions-tvf'
OUT.mkdir(parents=True, exist_ok=True)
LOGO = ROOT / 'assets' / 'logo-territoires-vivants-france-web.png'
GREEN = RGBColor(24,57,47); DARK = RGBColor(31,41,55); GRAY = RGBColor(102,112,133)
PALE='F3F7F2'; NOTE='FBF8EF'; BORDER='D9E0DC'
TVF = {'name':'Territoires Vivants France','subtitle':'Agence Territoriale de Revitalisation Immobilière','address':'25 rue Élise Gervais, 42000 Saint-Étienne','phone':'04 65 81 54 69','email':'contact@territoiresvivantsfrance.fr','site':'www.territoiresvivantsfrance.fr','rna':'RNA W922015538','siret':'SIRET 897 226 138 00018'}

CONVENTIONS = [
('convention-cadre-entreprise-partenaire-tvf','CONVENTION CADRE ENTREPRISE / PARTENAIRE','Expertise, partenariat territorial, mécénat, prestations et actions communes',[
('1. Parties et contexte',["La convention est conclue entre Territoires Vivants France, association loi 1901 agissant comme Agence Territoriale de Revitalisation Immobilière, et l’entreprise, fondation, association, organisme, professionnel ou partenaire souhaitant contribuer à une action de revitalisation.","Elle s’inscrit dans une logique de coopération territoriale : valoriser les compétences, ressources, expertises ou soutiens disponibles afin de contribuer à la remise en usage de biens, locaux, ressources ou projets utiles aux territoires." ]),
('2. Objet de la convention',["La convention définit le cadre général dans lequel le partenaire peut intervenir aux côtés de TVF : expertise, conseil, mécénat, mise à disposition de compétences, prestation, accompagnement, participation à une action ou contribution à un programme territorial.","Elle ne crée pas automatiquement une obligation de résultat, une exclusivité, un marché, une commande, une relation commerciale permanente ou une reconnaissance institutionnelle au-delà de ce qui est expressément prévu." ]),
('3. Formes possibles de coopération',["La coopération peut prendre plusieurs formes : apport d’expertise, participation à un groupe de travail, intervention technique, appui logistique, mécénat financier, mécénat en nature, mécénat de compétences, prestation encadrée, soutien à une action, parrainage ou partenariat opérationnel.","Chaque action concrète peut être précisée par une annexe, un bon de mission, un devis, une convention spécifique ou un programme d’action détaillé selon sa nature, son coût, sa durée et ses responsabilités." ]),
('4. Engagements de TVF',["TVF s’engage à présenter clairement les objectifs de la coopération, le cadre d’intervention, les projets concernés, les informations utiles et les limites de son rôle.","TVF veille à ne pas accepter de contribution inutile, inadaptée ou contraire à son objet. Elle conserve la faculté d’orienter, de suspendre ou de refuser une action lorsque les conditions de sécurité, de conformité, d’utilité ou de cohérence ne sont pas réunies." ]),
('5. Engagements du partenaire',["Le partenaire s’engage à intervenir dans le respect de ses compétences, assurances, habilitations, obligations professionnelles et règles de sécurité. Il s’engage à informer TVF de toute limite, incompatibilité, conflit d’intérêts ou contrainte susceptible d’affecter son intervention.","Lorsque le partenaire intervient auprès d’un propriétaire, d’une collectivité ou d’un tiers, les conditions de cette intervention doivent être clarifiées au préalable afin d’éviter toute confusion entre accompagnement TVF, prestation professionnelle, conseil réglementé ou mission indépendante." ]),
('6. Mécénat, dons et fiscalité',["Lorsque la coopération est présentée comme du mécénat, les parties vérifient préalablement que les conditions applicables sont réunies. Le soutien ne donne pas automatiquement droit à une réduction fiscale ou à un reçu fiscal.","Le partenaire demeure responsable de l’appréciation fiscale et comptable de sa contribution. TVF ne délivre un justificatif fiscal que lorsque le cadre légal, l’objet du soutien et l’absence de contrepartie substantielle le permettent." ]),
('7. Prestations et commandes',["Si l’intervention du partenaire donne lieu à une rémunération, un devis, une commande, une facture ou une prestation doivent préciser l’objet, le prix, les délais, les livrables, les responsabilités, les assurances et les conditions de validation.","La présente convention cadre ne remplace pas les documents contractuels spécifiques nécessaires à une prestation professionnelle, à des travaux, à une maîtrise d’œuvre, à un diagnostic réglementaire ou à une mission soumise à qualification." ]),
('8. Confidentialité et données',["Les informations relatives aux propriétaires, biens, documents, stratégies, partenaires, données économiques, projets ou difficultés identifiées sont confidentielles, sauf accord contraire ou nécessité d’exécution.","Lorsque des données personnelles sont échangées, chaque partie s’engage à respecter la réglementation applicable et à limiter l’accès aux seules personnes ayant besoin d’en connaître pour la mission concernée." ]),
('9. Communication et image',["L’utilisation du nom, logo, image, témoignage ou référence d’une partie nécessite son accord préalable. Toute communication doit rester exacte, proportionnée et ne pas présenter comme acquis un résultat, partenariat ou impact qui ne serait pas vérifié.","Les supports de communication peuvent mentionner l’action commune uniquement dans les conditions validées par les parties." ]),
('10. Durée, suivi et fin de coopération',["La convention est conclue pour une durée à compléter. Les parties peuvent prévoir des réunions de suivi, comptes rendus, bilans d’action ou indicateurs qualitatifs.","Chaque partie peut mettre fin à la coopération en cas de manquement, impossibilité, changement de contexte, absence de moyens, risque non maîtrisé ou décision commune de réorientation." ])], ['Fiche partenaire','Programme d’action','Devis ou bon de mission','Règles communication','Engagement confidentialité']),
('convention-mise-a-disposition-bien-tvf','CONVENTION DE MISE À DISPOSITION D’UN BIEN','Usage encadré, durée, accès, charges, assurance et restitution',[
('1. Parties et désignation du bien',["La convention est conclue entre TVF et le propriétaire, représentant ou titulaire habilité du bien mis à disposition. Le bien est décrit précisément : adresse, nature, surface approximative, dépendances, accès, état apparent et limites d’usage.","Une annexe d’état des lieux peut décrire les locaux, équipements, clés, compteurs, accès, photographies, réserves et restrictions connues au jour de la mise à disposition." ]),
('2. Objet et nature de la mise à disposition',["La convention a pour objet d’autoriser TVF, ou un projet expressément désigné, à utiliser le bien dans un cadre déterminé : stockage, action associative, atelier, occupation temporaire, projet solidaire, préparation de chantier, expérimentation territoriale ou autre usage validé.","Elle ne constitue pas automatiquement un bail d’habitation, bail commercial, bail professionnel, mandat de gestion, prêt illimité ou transfert de propriété. La qualification juridique doit être vérifiée selon la durée, l’usage, les contreparties et les obligations prévues." ]),
('3. Durée et conditions d’occupation',["La durée est fixée par les parties et peut être ponctuelle, temporaire, expérimentale ou renouvelable. Toute prolongation doit être formalisée par écrit.","Le propriétaire peut prévoir des conditions particulières d’accès, de jours et horaires, de présence, de fermeture, de clés, de stationnement, d’utilisation des parties communes ou d’interdiction de certaines zones." ]),
('4. Usage autorisé et interdictions',["Le bien ne peut être utilisé que pour l’usage expressément autorisé. Toute modification d’usage, sous-mise à disposition, accueil de public, activité commerciale, stockage sensible, travaux ou occupation par un tiers doit être validé au préalable.","Sont interdits sans accord écrit : transformation du bien, intervention lourde, modification des réseaux, hébergement non prévu, activité dangereuse, dépôt de produits interdits, nuisance anormale ou usage contraire aux règles applicables." ]),
('5. Charges, frais et fluides',["La convention précise la répartition des charges, consommations, fluides, entretien courant, déchets, nettoyage, abonnements, taxes ou frais liés à l’usage du bien.","Lorsque la mise à disposition est gratuite, une participation aux charges peut être prévue sans transformer automatiquement la nature de la convention. Les modalités doivent être clairement détaillées." ]),
('6. Assurance et responsabilité',["Le propriétaire conserve les assurances relevant de sa qualité et de son bien. TVF ou l’occupant autorisé doit disposer d’une assurance adaptée à son usage, couvrant notamment responsabilité civile, dommages éventuels et activités prévues.","Chaque partie demeure responsable des dommages causés par sa faute, son usage, ses intervenants ou les personnes placées sous sa responsabilité. Les sinistres doivent être signalés sans délai." ]),
('7. Accès, sécurité et état du bien',["TVF s’engage à respecter les conditions d’accès, les règles de sécurité et les limites fixées. Le propriétaire doit signaler les risques connus : structure, électricité, humidité, amiante, plomb, accès dangereux, servitudes, litiges ou restrictions.","Si un risque grave apparaît, l’usage peut être suspendu immédiatement jusqu’à clarification ou intervention d’un professionnel compétent." ]),
('8. Travaux, aménagements et entretien',["Aucun travaux, percement, modification, installation durable ou transformation ne peut être réalisé sans accord écrit du propriétaire. Les petits aménagements autorisés doivent être listés et leur sort à la restitution précisé.","L’entretien courant lié à l’usage peut être mis à la charge de TVF ou de l’occupant autorisé. Les réparations structurelles ou obligations du propriétaire restent à clarifier selon la situation." ]),
('9. Restitution du bien',["À l’issue de la mise à disposition, le bien est restitué dans l’état convenu, sous réserve de l’usure normale et des éléments expressément acceptés. Un état des lieux de sortie peut être établi.","Les clés, badges, documents, équipements ou accès remis doivent être restitués. Les biens, matériaux ou installations ajoutés sont retirés sauf accord contraire." ]),
('10. Fin anticipée et litiges',["La convention peut prendre fin par arrivée du terme, accord des parties, non-respect des conditions, danger, impossibilité d’usage, retrait du projet ou nécessité impérieuse du propriétaire.","Les parties recherchent prioritairement une solution amiable. Les clauses particulières peuvent prévoir les modalités de préavis, restitution et traitement des frais engagés." ])], ['Désignation du bien','État des lieux entrée','Autorisation photos','Attestation assurance','État des lieux sortie']),
('convention-projet-solidaire-association-tvf','CONVENTION PROJET SOLIDAIRE / ASSOCIATION','Projet commun, utilité sociale, ressources, sécurité, bénévoles et suivi',[
('1. Parties et finalité du projet',["La convention est conclue entre TVF et l’association, structure d’insertion, organisme de formation, porteur de projet ou collectif engagé dans une action sociale, solidaire, éducative, culturelle, environnementale ou territoriale.","Elle vise à encadrer une coopération contribuant à la revitalisation, à l’inclusion, au réemploi, à l’apprentissage, à l’amélioration du cadre de vie ou à l’activation temporaire d’un bien, d’un espace ou d’une ressource." ]),
('2. Objet du partenariat',["La convention définit le projet, ses objectifs, le public concerné, le territoire, les moyens mobilisés, les responsabilités respectives, les étapes, la durée et les conditions de suivi.","Elle ne crée pas automatiquement de droit d’usage sur un bien, de financement, de mise à disposition de ressources ou d’intervention de TVF au-delà des engagements expressément prévus." ]),
('3. Description du projet',["Le projet est décrit en annexe : contexte, objectifs, bénéficiaires, lieu, calendrier, besoins matériels, ressources humaines, partenaires, budget prévisionnel, indicateurs de suivi et conditions de réussite.","TVF peut demander des précisions lorsque le projet implique un public vulnérable, des bénévoles, des mineurs, de l’outillage, un chantier, un accueil de public ou l’utilisation d’un bien privé." ]),
('4. Rôle de TVF',["TVF peut contribuer par la coordination, l’orientation, la mise en relation, l’appui documentaire, la mobilisation de ressources, le lien avec un propriétaire, l’identification d’un lieu, le suivi du dossier ou la valorisation institutionnelle du projet.","TVF ne se substitue pas à l’association porteuse, aux employeurs, aux encadrants techniques, aux organismes de formation, aux professionnels habilités ou aux autorités compétentes." ]),
('5. Rôle du partenaire associatif',["Le partenaire porte son projet, encadre ses équipes, bénévoles, salariés, bénéficiaires ou participants, respecte ses obligations légales, assure la sécurité des personnes et dispose des assurances nécessaires.","Il s’engage à informer TVF de toute difficulté, incident, modification du projet, changement d’usage, besoin supplémentaire ou risque susceptible d’affecter la coopération." ]),
('6. Utilisation d’un bien ou d’un espace',["Si le projet nécessite l’usage d’un bien, local, terrain ou espace, cet usage doit être autorisé par le propriétaire ou la personne habilitée et, si nécessaire, faire l’objet d’une convention de mise à disposition distincte ou d’une annexe dédiée.","Aucune occupation, intervention ou activité ne peut être organisée dans un lieu sans autorisation claire, conditions de sécurité suffisantes et assurance adaptée." ]),
('7. Ressources, matériaux et équipements',["Lorsque TVF met à disposition des matériaux, équipements ou ressources, leur nature, quantité, usage prévu, conditions de transport, stockage, responsabilité et restitution éventuelle sont précisées.","Les ressources ne doivent pas être revendues, détournées de leur objet ou utilisées dans un cadre différent sans accord préalable." ]),
('8. Sécurité, encadrement et bénévoles',["Les activités impliquant chantier, outillage, manutention, travaux, accueil de public ou participation de bénévoles doivent être encadrées par des personnes compétentes et réalisées dans des conditions de sécurité adaptées.","Les participants doivent être informés des règles applicables. Les missions nécessitant qualification, assurance, autorisation ou compétence professionnelle doivent être confiées à des intervenants habilités." ]),
('9. Communication, image et données',["Toute communication sur le projet doit respecter l’image des personnes, l’accord des partenaires, la confidentialité des lieux et la protection des données personnelles.","L’utilisation de photos, témoignages, noms, logos ou informations concernant les bénéficiaires nécessite les autorisations adaptées, notamment lorsque des personnes vulnérables ou mineures sont concernées." ]),
('10. Suivi, bilan et fin du partenariat',["Les parties peuvent prévoir réunions, compte rendu, bilan, photos avant/après, indicateurs qualitatifs, retour d’expérience et perspectives de poursuite.","La convention peut prendre fin en cas de terme, réalisation du projet, accord des parties, impossibilité, risque non maîtrisé, non-respect des engagements ou absence de moyens suffisants." ])], ['Fiche projet','Calendrier d’action','Liste ressources mobilisées','Attestations assurance','Autorisation image et communication'])
]

def shade(cell, fill):
    tcPr=cell._tc.get_or_add_tcPr(); shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),fill); tcPr.append(shd)
def borders(cell):
    tcPr=cell._tc.get_or_add_tcPr(); tb=tcPr.first_child_found_in('w:tcBorders')
    if tb is None: tb=OxmlElement('w:tcBorders'); tcPr.append(tb)
    for e in ('top','left','bottom','right'):
        el=tb.find(qn('w:'+e))
        if el is None: el=OxmlElement('w:'+e); tb.append(el)
        el.set(qn('w:val'),'single'); el.set(qn('w:sz'),'8'); el.set(qn('w:color'),BORDER)
def run(p,text,size=10,bold=False,color=DARK,font='Inter'):
    r=p.add_run(text); r.font.name=font; r.font.size=Pt(size); r.bold=bold; r.font.color.rgb=color; return r
def cell(cell,text,bold=False,fill=None):
    cell.text='';
    if fill: shade(cell,fill)
    p=cell.paragraphs[0]; p.paragraph_format.space_after=Pt(0); run(p,text,8.5,bold,GREEN if bold else DARK); cell.vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER; borders(cell)
def note(doc,text):
    t=doc.add_table(rows=1,cols=1); t.alignment=WD_TABLE_ALIGNMENT.CENTER; cell(t.rows[0].cells[0],text,False,NOTE)
    for rr in t.rows[0].cells[0].paragraphs[0].runs: rr.font.size=Pt(8); rr.font.color.rgb=GRAY
def fields(doc):
    t=doc.add_table(rows=4,cols=2); t.alignment=WD_TABLE_ALIGNMENT.CENTER; t.columns[0].width=Inches(2.25); t.columns[1].width=Inches(4.5)
    for i,(a,b) in enumerate([('Référence interne TVF','[à compléter]'),('Parties signataires','[à compléter]'),('Date d’effet','[à compléter]'),('Durée','[à compléter]')]): cell(t.rows[i].cells[0],a,True,PALE); cell(t.rows[i].cells[1],b)
def make_docx(slug,title,sub,arts,annexes):
    doc=Document(); sec=doc.sections[0]; sec.top_margin=Inches(.55); sec.bottom_margin=Inches(.55); sec.left_margin=Inches(.65); sec.right_margin=Inches(.65)
    h=doc.add_table(rows=1,cols=2); h.alignment=WD_TABLE_ALIGNMENT.CENTER; h.columns[0].width=Inches(1.25); h.columns[1].width=Inches(5.5)
    if LOGO.exists(): h.rows[0].cells[0].paragraphs[0].add_run().add_picture(str(LOGO), width=Inches(1.0))
    p=h.rows[0].cells[1].paragraphs[0]; p.alignment=WD_ALIGN_PARAGRAPH.RIGHT; run(p,TVF['name']+'\n',12,True,GREEN,'Manrope'); run(p,TVF['subtitle']+'\n',8.5,False,DARK); run(p,f"{TVF['address']} | {TVF['phone']} | {TVF['email']}\n{TVF['rna']} | {TVF['siret']}",7.2,False,GRAY)
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; p.paragraph_format.space_before=Pt(10); run(p,title,18,True,GREEN,'Manrope')
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER; run(p,sub,10,False,GRAY)
    note(doc,"MODÈLE INTERNE À ADAPTER — Document institutionnel de travail. Toute signature réelle doit être précédée d’une vérification juridique adaptée à la situation, aux parties, aux responsabilités et au cadre réglementaire applicable.")
    fields(doc)
    for head,paras in arts:
        p=doc.add_paragraph(); p.paragraph_format.space_before=Pt(9); run(p,head,12,True,GREEN,'Manrope')
        for para in paras:
            q=doc.add_paragraph(); q.paragraph_format.line_spacing=1.12; q.paragraph_format.space_after=Pt(5); run(q,para,9.6,False,DARK)
    p=doc.add_paragraph(); run(p,'Annexes recommandées',12,True,GREEN,'Manrope')
    for a in annexes:
        q=doc.add_paragraph(); q.paragraph_format.left_indent=Inches(.18); run(q,'□ '+a,9.5,False,DARK)
    p=doc.add_paragraph(); run(p,'Signatures',12,True,GREEN,'Manrope')
    sig=doc.add_table(rows=3,cols=2); sig.alignment=WD_TABLE_ALIGNMENT.CENTER
    for i,row in enumerate([('Pour Territoires Vivants France','Pour la partie cocontractante'),('Nom, qualité, date','Nom, qualité, date'),('Signature','Signature')]):
        for c,t in enumerate(row): cell(sig.rows[i].cells[c],t,i==0,PALE if i==0 else None)
    f=doc.sections[0].footer.paragraphs[0]; f.alignment=WD_ALIGN_PARAGRAPH.CENTER; run(f,f"{TVF['name']} — {title} — modèle interne confidentiel",7,False,GRAY)
    path=OUT/(slug+'.docx'); doc.save(path); return path
def make_pdf(slug,title,sub,arts,annexes):
    st=getSampleStyleSheet(); st.add(ParagraphStyle(name='T',fontName='Helvetica-Bold',fontSize=17,leading=21,textColor=colors.HexColor('#18392F'),alignment=1)); st.add(ParagraphStyle(name='S',fontSize=9.5,leading=12,textColor=colors.HexColor('#667085'),alignment=1,spaceAfter=8)); st.add(ParagraphStyle(name='H',fontName='Helvetica-Bold',fontSize=11.5,leading=14,textColor=colors.HexColor('#18392F'),spaceBefore=9,spaceAfter=3)); st.add(ParagraphStyle(name='B',fontSize=9.1,leading=12,textColor=colors.HexColor('#1F2937'),spaceAfter=5)); st.add(ParagraphStyle(name='N',fontSize=8,leading=10.5,textColor=colors.HexColor('#475467'),backColor=colors.HexColor('#FBF8EF'),borderColor=colors.HexColor('#E4D7B8'),borderWidth=.5,borderPadding=6,spaceAfter=8)); st.add(ParagraphStyle(name='Small',fontSize=7.2,leading=9,textColor=colors.HexColor('#667085')))
    story=[]; logo=Image(str(LOGO), width=24*mm, height=18*mm) if LOGO.exists() else ''
    ht=Table([[logo,Paragraph(f"<b>{TVF['name']}</b><br/>{TVF['subtitle']}<br/>{TVF['address']} | {TVF['phone']} | {TVF['email']}<br/>{TVF['rna']} | {TVF['siret']}",st['Small'])]],colWidths=[30*mm,140*mm]); ht.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('ALIGN',(1,0),(1,0),'RIGHT')])) ; story.append(ht); story.append(Spacer(1,7*mm)); story.append(Paragraph(title,st['T'])); story.append(Paragraph(sub,st['S'])); story.append(Paragraph('MODÈLE INTERNE À ADAPTER — Document institutionnel de travail. Toute signature réelle doit être précédée d’une vérification juridique adaptée.',st['N']))
    tbl=Table([('Référence interne TVF','[à compléter]'),('Parties signataires','[à compléter]'),('Date d’effet','[à compléter]'),('Durée','[à compléter]')],colWidths=[50*mm,120*mm]); tbl.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.45,colors.HexColor('#D9E0DC')),('BACKGROUND',(0,0),(0,-1),colors.HexColor('#F3F7F2')),('FONTNAME',(0,0),(0,-1),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),7.8),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); story.append(tbl)
    for h,paras in arts:
        story.append(Paragraph(h,st['H']))
        for para in paras: story.append(Paragraph(para,st['B']))
    story.append(Paragraph('Annexes recommandées',st['H']))
    for a in annexes: story.append(Paragraph('□ '+a,st['B']))
    story.append(Paragraph('Signatures',st['H'])); sig=Table([['Pour Territoires Vivants France','Pour la partie cocontractante'],['Nom, qualité, date','Nom, qualité, date'],['Signature','Signature']],colWidths=[85*mm,85*mm],rowHeights=[9*mm,9*mm,22*mm]); sig.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.45,colors.HexColor('#D9E0DC')),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#F3F7F2')),('ALIGN',(0,0),(-1,-1),'CENTER'),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('FONTSIZE',(0,0),(-1,-1),8)])); story.append(sig)
    path=OUT/(slug+'.pdf'); SimpleDocTemplate(str(path),pagesize=A4,rightMargin=14*mm,leftMargin=14*mm,topMargin=11*mm,bottomMargin=12*mm).build(story); return path
for slug,title,sub,arts,annexes in CONVENTIONS:
    print(make_docx(slug,title,sub,arts,annexes)); print(make_pdf(slug,title,sub,arts,annexes))
