const crypto = require("crypto");

const OUTBOUND_TIMEOUT_MS = Number(process.env.TVF_OUTBOUND_TIMEOUT_MS || 9000);
const RISK_TYPES = new Set(["rgpd", "image_rights", "visit_authorization", "insurance", "field_safety", "conflict_interest", "sensitive_data", "financial", "legal", "operational", "incident", "other"]);
const RISK_STATUSES = new Set(["open", "mitigating", "blocked", "accepted", "resolved", "closed", "archive"]);
const CHECK_TYPES = new Set(["rgpd", "image_rights", "visit_authorization", "insurance", "field_safety", "conflict_interest", "publication", "document", "audit", "other"]);
const CHECK_STATUSES = new Set(["missing", "to_review", "valid", "expired", "rejected", "waived", "archive"]);
const INCIDENT_TYPES = new Set(["rgpd", "security", "field", "insurance", "image_rights", "conflict_interest", "financial", "operational", "other"]);
const INCIDENT_STATUSES = new Set(["new", "triage", "investigating", "corrective_action", "closed", "archive"]);
const CONSENT_TYPES = new Set(["data_processing", "image_rights", "visit_authorization", "newsletter", "minor_authorization", "other"]);
const CONSENT_STATUSES = new Set(["pending", "valid", "expired", "revoked", "rejected", "archive"]);
const SEVERITIES = new Set(["low", "medium", "high", "critical"]);
const LIKELIHOODS = new Set(["rare", "possible", "likely", "almost_certain"]);
const RELATED_TYPES = new Set(["none", "request", "case", "contact", "organization", "document", "procedure", "knowledge", "branch", "project", "finance", "impact", "decision", "committee", "event"]);

function sendJson(res, statusCode, payload) { res.statusCode = statusCode; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(payload)); }
function clean(value, max = 1200) { if (typeof value !== "string") return ""; return value.replace(/\s+/g, " ").trim().slice(0, max); }
function cleanEnvToken(value, max = 3000) { return clean(value || "", max).replace(/^[`'\",;]+|[`'\",;]+$/g, "").replace(/\s+/g, ""); }
function cleanEnvUrl(value) { return clean(value || "", 600).replace(/^[`'\",;]+|[`'\",;]+$/g, ""); }
function normalizeSupabaseRestUrl(rawUrl) { const cleaned = cleanEnvUrl(rawUrl).replace(/\/+$/, ""); if (!cleaned) return ""; return cleaned.endsWith("/rest/v1") ? cleaned : `${cleaned}/rest/v1`; }
async function readJsonBody(req) { let body = ""; for await (const chunk of req) { body += chunk; if (body.length > 90 * 1024) throw Object.assign(new Error("Payload trop volumineux."), { statusCode: 413 }); } if (!body) return {}; try { return JSON.parse(body); } catch { throw Object.assign(new Error("JSON invalide."), { statusCode: 400 }); } }
function adminToken() { return cleanEnvToken(process.env.TVF_ADMIN_TOKEN || process.env.ADMIN_TOKEN || "", 3000); }
function tokenFromRequest(req) { const authorization = clean(req.headers.authorization || "", 4000); if (authorization.toLowerCase().startsWith("bearer ")) return cleanEnvToken(authorization.slice(7), 3000); return cleanEnvToken(req.headers["x-admin-token"] || "", 3000); }
function safeEqual(a, b) { if (!a || !b) return false; const left = Buffer.from(a); const right = Buffer.from(b); if (left.length !== right.length) return false; return crypto.timingSafeEqual(left, right); }
function requireAdmin(req) { const expected = adminToken(); if (!expected) throw Object.assign(new Error("Back-office non configure : ajoutez TVF_ADMIN_TOKEN dans Vercel."), { statusCode: 503, code: "ADMIN_TOKEN_MISSING" }); if (!safeEqual(tokenFromRequest(req), expected)) throw Object.assign(new Error("Acces admin refuse."), { statusCode: 401, code: "ADMIN_UNAUTHORIZED" }); }
function supabaseConfig() { const restUrl = normalizeSupabaseRestUrl(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL); const key = cleanEnvToken(process.env.SUPABASE_SERVICE_ROLE_KEY || "", 3000); if (!restUrl || !key) throw Object.assign(new Error("Supabase admin non configure : SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY sont requis."), { statusCode: 503, code: "SUPABASE_ADMIN_NOT_CONFIGURED" }); return { restUrl, key }; }
function supabaseHeaders(key, extra = {}) { const headers = { apikey: key, "Content-Type": "application/json", ...extra }; if (!key.startsWith("sb_")) headers.Authorization = `Bearer ${key}`; return headers; }
async function fetchWithTimeout(url, options = {}) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), OUTBOUND_TIMEOUT_MS); try { return await fetch(url, { ...options, signal: controller.signal }); } finally { clearTimeout(timeout); } }
async function supabaseRequest(path, options = {}) { const { restUrl, key } = supabaseConfig(); const response = await fetchWithTimeout(`${restUrl}/${path}`, { ...options, headers: supabaseHeaders(key, options.headers || {}) }); const text = await response.text(); if (!response.ok) throw Object.assign(new Error("Requete Supabase impossible."), { statusCode: 502, details: text }); return text ? JSON.parse(text) : null; }
function queryUrl(req) { return new URL(req.url, "https://admin.local"); }
function validateEnum(set, value, message) { if (value && !set.has(value)) throw Object.assign(new Error(message), { statusCode: 400 }); }
function validateUuid(value, label = "Identifiant") { const cleaned = clean(value || "", 80); if (cleaned && !/^[0-9a-f-]{32,36}$/i.test(cleaned)) throw Object.assign(new Error(`${label} invalide.`), { statusCode: 400 }); return cleaned || null; }
function dateTimeValue(value) { const text = clean(value || "", 80); if (!text) return null; const time = new Date(text).getTime(); return Number.isNaN(time) ? null : new Date(time).toISOString(); }
function dateValue(value) { const text = clean(value || "", 80); if (!text) return null; const time = new Date(text).getTime(); return Number.isNaN(time) ? null : new Date(time).toISOString().slice(0, 10); }
function compactPayload(fields, input, partial, defaults = []) { const payload = {}; Object.entries(fields).forEach(([key, value]) => { if (!partial || Object.prototype.hasOwnProperty.call(input, key) || defaults.includes(key)) { if (value !== "" && value !== undefined) payload[key] = value; else if (partial && Object.prototype.hasOwnProperty.call(input, key)) payload[key] = null; } }); return payload; }
function percent(done, total) { if (!total) return 100; return Math.round((done / total) * 100); }
function autoKey(prefix) { return `${prefix}-${new Date().toISOString().slice(0, 10).replace(/-/g, "")}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`; }

function riskPayload(input, partial = false) {
  const type = clean(input.risk_type || "", 80) || (!partial ? "operational" : ""); const severity = clean(input.severity || "", 80) || (!partial ? "medium" : ""); const likelihood = clean(input.likelihood || "", 80) || (!partial ? "possible" : ""); const status = clean(input.status || "", 80) || (!partial ? "open" : ""); const related = clean(input.related_object_type || "", 80) || (!partial ? "none" : "");
  validateEnum(RISK_TYPES, type, "Type de risque invalide."); validateEnum(SEVERITIES, severity, "Severite invalide."); validateEnum(LIKELIHOODS, likelihood, "Probabilite invalide."); validateEnum(RISK_STATUSES, status, "Statut risque invalide."); validateEnum(RELATED_TYPES, related, "Objet lie invalide.");
  const fields = { branch_id: validateUuid(input.branch_id || "", "Antenne"), risk_key: clean(input.risk_key || "", 120) || (!partial ? autoKey("RISK") : ""), risk_type: type, severity, likelihood, status, title: clean(input.title || "", 280), description: clean(input.description || input.summary || "", 4000), mitigation_plan: clean(input.mitigation_plan || "", 4000), owner_name: clean(input.owner_name || "", 180), related_object_type: related, related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), due_at: dateTimeValue(input.due_at), reviewed_at: dateTimeValue(input.reviewed_at), ai_summary: clean(input.ai_summary || "", 1200), created_by: clean(input.created_by || "TVF OS", 180) };
  if (!partial && !fields.title) throw Object.assign(new Error("Titre de risque requis."), { statusCode: 400 });
  return compactPayload(fields, input, partial, ["risk_type", "severity", "likelihood", "status", "related_object_type"]);
}
function checkPayload(input, partial = false) { const type = clean(input.check_type || "", 80) || (!partial ? "rgpd" : ""); const status = clean(input.status || "", 80) || (!partial ? "missing" : ""); const related = clean(input.related_object_type || "", 80) || (!partial ? "none" : ""); validateEnum(CHECK_TYPES, type, "Type de controle invalide."); validateEnum(CHECK_STATUSES, status, "Statut controle invalide."); validateEnum(RELATED_TYPES, related, "Objet lie invalide."); const fields = { branch_id: validateUuid(input.branch_id || "", "Antenne"), check_key: clean(input.check_key || "", 120) || (!partial ? autoKey("CHECK") : ""), check_type: type, title: clean(input.title || "", 280), status, required: input.required === false || input.required === "false" ? false : true, blocking: input.blocking === true || input.blocking === "true", related_object_type: related, related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), evidence_document_id: validateUuid(input.evidence_document_id || "", "Document"), owner_name: clean(input.owner_name || "", 180), due_at: dateTimeValue(input.due_at), completed_at: status === "valid" ? (dateTimeValue(input.completed_at) || new Date().toISOString()) : null, notes: clean(input.notes || input.summary || "", 2200), ai_summary: clean(input.ai_summary || "", 1200) }; if (!partial && !fields.title) throw Object.assign(new Error("Titre de controle requis."), { statusCode: 400 }); return compactPayload(fields, input, partial, ["check_type", "status", "required", "blocking", "related_object_type"]); }
function incidentPayload(input, partial = false) { const type = clean(input.incident_type || "", 80) || (!partial ? "operational" : ""); const severity = clean(input.severity || "", 80) || (!partial ? "medium" : ""); const status = clean(input.status || "", 80) || (!partial ? "new" : ""); const related = clean(input.related_object_type || "", 80) || (!partial ? "none" : ""); validateEnum(INCIDENT_TYPES, type, "Type incident invalide."); validateEnum(SEVERITIES, severity, "Severite invalide."); validateEnum(INCIDENT_STATUSES, status, "Statut incident invalide."); validateEnum(RELATED_TYPES, related, "Objet lie invalide."); const fields = { branch_id: validateUuid(input.branch_id || "", "Antenne"), incident_key: clean(input.incident_key || "", 120) || (!partial ? autoKey("INC") : ""), incident_type: type, severity, status, title: clean(input.title || "", 280), description: clean(input.description || input.summary || "", 4000), occurred_at: dateTimeValue(input.occurred_at), reported_by: clean(input.reported_by || "", 180), owner_name: clean(input.owner_name || "", 180), immediate_actions: clean(input.immediate_actions || "", 2200), corrective_actions: clean(input.corrective_actions || "", 2200), related_object_type: related, related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), closed_at: status === "closed" ? (dateTimeValue(input.closed_at) || new Date().toISOString()) : null, ai_summary: clean(input.ai_summary || "", 1200) }; if (!partial && !fields.title) throw Object.assign(new Error("Titre incident requis."), { statusCode: 400 }); return compactPayload(fields, input, partial, ["incident_type", "severity", "status", "related_object_type"]); }
function consentPayload(input, partial = false) { const type = clean(input.consent_type || "", 80) || (!partial ? "data_processing" : ""); const status = clean(input.status || "", 80) || (!partial ? "pending" : ""); const related = clean(input.related_object_type || "", 80) || (!partial ? "none" : ""); validateEnum(CONSENT_TYPES, type, "Type consentement invalide."); validateEnum(CONSENT_STATUSES, status, "Statut consentement invalide."); validateEnum(RELATED_TYPES, related, "Objet lie invalide."); const fields = { branch_id: validateUuid(input.branch_id || "", "Antenne"), person_name: clean(input.person_name || input.title || "", 220), consent_type: type, status, related_object_type: related, related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), evidence_document_id: validateUuid(input.evidence_document_id || "", "Document"), valid_from: dateValue(input.valid_from), valid_until: dateValue(input.valid_until), notes: clean(input.notes || input.summary || "", 1800) }; if (!partial && !fields.person_name) throw Object.assign(new Error("Personne concernee requise."), { statusCode: 400 }); return compactPayload(fields, input, partial, ["consent_type", "status", "related_object_type"]); }

function riskScore(row = {}) { const sev = { low: 1, medium: 2, high: 3, critical: 4 }[row.severity] || 1; const like = { rare: 1, possible: 2, likely: 3, almost_certain: 4 }[row.likelihood] || 1; return sev * like; }
function riskAssistant(risk = {}, checks = []) { const linkedBlocking = checks.filter((c) => c.blocking && !["valid", "waived", "archive"].includes(c.status)); const overdue = risk.due_at && new Date(risk.due_at) < new Date() && !["resolved", "closed", "archive"].includes(risk.status); const score = riskScore(risk); const level = score >= 12 ? "critique" : score >= 8 ? "eleve" : score >= 4 ? "modere" : "faible"; return { score, level, blocking_checks: linkedBlocking.length, overdue: Boolean(overdue), should_block: level === "critique" || linkedBlocking.length > 0, summary: `${risk.title || "Risque"} : niveau ${level}, ${linkedBlocking.length} controle(s) bloquant(s).`, recommended_actions: linkedBlocking.length ? ["Bloquer l'action sensible", "Collecter la preuve manquante", "Demander validation conformite"] : overdue ? ["Relancer le responsable", "Replanifier la mesure corrective"] : ["Suivre le plan de mitigation", "Documenter la prochaine revue"] }; }
function complianceAssistant(checks = [], risks = [], incidents = [], consents = []) { const blocking = checks.filter((c) => c.blocking && !["valid", "waived", "archive"].includes(c.status)); const missing = checks.filter((c) => ["missing", "expired", "rejected"].includes(c.status)); const openRisks = risks.filter((r) => !["resolved", "closed", "archive"].includes(r.status)); const criticalRisks = openRisks.filter((r) => ["critical", "high"].includes(r.severity)); const openIncidents = incidents.filter((i) => !["closed", "archive"].includes(i.status)); const pendingConsents = consents.filter((c) => ["pending", "expired", "revoked", "rejected"].includes(c.status)); const validChecks = checks.filter((c) => ["valid", "waived"].includes(c.status)).length; const score = percent(validChecks, checks.filter((c) => c.required).length || checks.length); return { compliance_score: score, blocking_count: blocking.length, missing_count: missing.length, open_risks: openRisks.length, critical_risks: criticalRisks.length, open_incidents: openIncidents.length, pending_consents: pendingConsents.length, summary: `${score}% de conformite, ${blocking.length} blocage(s), ${criticalRisks.length} risque(s) critique/eleve, ${openIncidents.length} incident(s) ouvert(s).`, priorities: [blocking.length ? "Traiter les controles bloquants" : "Aucun blocage actif", criticalRisks.length ? "Reduire les risques critiques" : "Risques critiques sous controle", pendingConsents.length ? "Regulariser les consentements" : "Consentements sous controle" ] }; }
function enrichRisks(risks = [], checks = []) { return risks.map((risk) => ({ ...risk, assistant: riskAssistant(risk, checks.filter((c) => c.related_object_id && c.related_object_id === risk.related_object_id)) })); }

function addFilters(params, url, set, searchColumns = ["title", "description"]) { const status = clean(url.searchParams.get("status") || "", 80); const q = clean(url.searchParams.get("q") || "", 180).replace(/[*,()]/g, " "); if (status && status !== "all" && set.has(status)) params.set("status", `eq.${status}`); if (q) params.set("or", `(${searchColumns.map((c) => `${c}.ilike.*${q}*`).join(",")})`); }
async function listTable(req, table, set, order = "updated_at.desc", searchColumns) { const url = queryUrl(req); const params = new URLSearchParams({ select: "*", order, limit: String(Math.min(Math.max(Number(url.searchParams.get("limit") || 240), 1), 900)) }); addFilters(params, url, set, searchColumns); const branchId = validateUuid(url.searchParams.get("branch_id") || "", "Antenne"); if (branchId) params.set("branch_id", `eq.${branchId}`); return supabaseRequest(`${table}?${params.toString()}`); }
async function dashboard() { const [risks, checks, incidents, consents, logs] = await Promise.all([supabaseRequest("risks?select=*&limit=900"), supabaseRequest("compliance_checks?select=*&limit=1200"), supabaseRequest("incidents?select=*&limit=600"), supabaseRequest("consent_records?select=*&limit=800"), supabaseRequest("audit_logs?select=*&order=created_at.desc&limit=120")]); const assistant = complianceAssistant(checks || [], risks || [], incidents || [], consents || []); return { total_risks: (risks || []).length, open_risks: assistant.open_risks, critical_risks: assistant.critical_risks, blocking_checks: assistant.blocking_count, missing_checks: assistant.missing_count, open_incidents: assistant.open_incidents, pending_consents: assistant.pending_consents, audit_events: (logs || []).length, compliance_score: assistant.compliance_score, alerts: [...enrichRisks(risks || [], checks || []).filter((r) => r.assistant.should_block || r.assistant.overdue).slice(0, 8), ...(checks || []).filter((c) => c.blocking && !["valid", "waived", "archive"].includes(c.status)).slice(0, 5).map((c) => ({ title: c.title, status: c.status, assistant: { summary: `Controle bloquant : ${c.title}` } }))], assistant }; }
async function listRisks(req) { const risks = await listTable(req, "risks", RISK_STATUSES, "updated_at.desc", ["title", "description", "mitigation_plan", "risk_key"]); const checks = await supabaseRequest("compliance_checks?select=*&limit=1200"); return enrichRisks(risks || [], checks || []); }
async function createRecord(table, payload) { const rows = await supabaseRequest(`${table}?select=*`, { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function updateRecord(table, id, payload) { const rows = await supabaseRequest(`${table}?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function audit(action, objectType, objectId, after = {}) { return createRecord("audit_logs", { actor_name: "TVF OS", action, object_type: objectType, object_id: objectId || null, severity: after.severity === "critical" ? "critical" : "notice", after_snapshot: after }).catch(() => null); }

module.exports = async function handler(req, res) {
  if (req.method === "OPTIONS") { res.statusCode = 204; res.end(); return; }
  try {
    requireAdmin(req);
    if (req.method === "GET") {
      const entity = clean(queryUrl(req).searchParams.get("entity") || "dashboard", 80);
      if (entity === "dashboard") return sendJson(res, 200, { ok: true, dashboard: await dashboard() });
      if (entity === "risks") return sendJson(res, 200, { ok: true, risks: await listRisks(req) });
      if (entity === "checks") return sendJson(res, 200, { ok: true, checks: await listTable(req, "compliance_checks", CHECK_STATUSES, "updated_at.desc", ["title", "notes", "check_key"]) });
      if (entity === "incidents") return sendJson(res, 200, { ok: true, incidents: await listTable(req, "incidents", INCIDENT_STATUSES, "updated_at.desc", ["title", "description", "incident_key"]) });
      if (entity === "consents") return sendJson(res, 200, { ok: true, consents: await listTable(req, "consent_records", CONSENT_STATUSES, "updated_at.desc", ["person_name", "notes"]) });
      if (entity === "audit") return sendJson(res, 200, { ok: true, audit_logs: await supabaseRequest("audit_logs?select=*&order=created_at.desc&limit=300") });
      throw Object.assign(new Error("Entite inconnue."), { statusCode: 400 });
    }
    const input = await readJsonBody(req);
    const type = clean(input.type || "risk", 80);
    if (req.method === "POST") {
      if (type === "risk") { const risk = await createRecord("risks", riskPayload(input)); await audit("create_risk", "risk", risk.id, risk); return sendJson(res, 201, { ok: true, risk }); }
      if (type === "check") { const check = await createRecord("compliance_checks", checkPayload(input)); await audit("create_check", "compliance_check", check.id, check); return sendJson(res, 201, { ok: true, check }); }
      if (type === "incident") { const incident = await createRecord("incidents", incidentPayload(input)); await audit("create_incident", "incident", incident.id, incident); return sendJson(res, 201, { ok: true, incident }); }
      if (type === "consent") { const consent = await createRecord("consent_records", consentPayload(input)); await audit("create_consent", "consent", consent.id, consent); return sendJson(res, 201, { ok: true, consent }); }
    }
    if (req.method === "PATCH") {
      const id = validateUuid(input.id || "", "Identifiant"); if (!id) throw Object.assign(new Error("Identifiant requis."), { statusCode: 400 });
      if (type === "risk") { const risk = await updateRecord("risks", id, riskPayload(input, true)); await audit("update_risk", "risk", id, risk); return sendJson(res, 200, { ok: true, risk }); }
      if (type === "check") { const check = await updateRecord("compliance_checks", id, checkPayload(input, true)); await audit("update_check", "compliance_check", id, check); return sendJson(res, 200, { ok: true, check }); }
      if (type === "incident") { const incident = await updateRecord("incidents", id, incidentPayload(input, true)); await audit("update_incident", "incident", id, incident); return sendJson(res, 200, { ok: true, incident }); }
      if (type === "consent") { const consent = await updateRecord("consent_records", id, consentPayload(input, true)); await audit("update_consent", "consent", id, consent); return sendJson(res, 200, { ok: true, consent }); }
    }
    sendJson(res, 405, { ok: false, error: "Methode non autorisee." });
  } catch (error) {
    const statusCode = error.statusCode || 500;
    sendJson(res, statusCode, { ok: false, error: statusCode >= 500 ? "Risques et conformite indisponibles pour le moment." : error.message, code: error.code || undefined, details: process.env.NODE_ENV === "development" ? error.details || error.message : undefined });
  }
};

module.exports._private = { normalizeSupabaseRestUrl, riskPayload, checkPayload, incidentPayload, consentPayload, riskScore, riskAssistant, complianceAssistant, percent };
