const crypto = require("crypto");
const OUTBOUND_TIMEOUT_MS = Number(process.env.TVF_OUTBOUND_TIMEOUT_MS || 9000);
const PROJECT_STATUSES = new Set(["draft", "active", "paused", "completed", "cancelled", "archive"]);
const TASK_STATUSES = new Set(["todo", "doing", "waiting", "done", "cancelled", "archive"]);
const EVENT_STATUSES = new Set(["scheduled", "confirmed", "done", "cancelled", "archive"]);
const RULE_STATUSES = new Set(["active", "paused", "archive"]);
const PRIORITIES = new Set(["P1", "P2", "P3"]);
function sendJson(res, statusCode, payload) { res.statusCode = statusCode; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(payload)); }
function clean(value, max = 1200) { if (typeof value !== "string") return ""; return value.replace(/\s+/g, " ").trim().slice(0, max); }
function cleanEnvToken(value, max = 3000) { return clean(value || "", max).replace(/^[`'\",;]+|[`'\",;]+$/g, "").replace(/\s+/g, ""); }
function cleanEnvUrl(value) { return clean(value || "", 600).replace(/^[`'\",;]+|[`'\",;]+$/g, ""); }
function normalizeSupabaseRestUrl(rawUrl) { const cleaned = cleanEnvUrl(rawUrl).replace(/\/+$/, ""); if (!cleaned) return ""; return cleaned.endsWith("/rest/v1") ? cleaned : `${cleaned}/rest/v1`; }
async function readJsonBody(req) { let body = ""; for await (const chunk of req) { body += chunk; if (body.length > 100 * 1024) throw Object.assign(new Error("Payload trop volumineux."), { statusCode: 413 }); } if (!body) return {}; try { return JSON.parse(body); } catch { throw Object.assign(new Error("JSON invalide."), { statusCode: 400 }); } }
function adminToken() { return cleanEnvToken(process.env.TVF_ADMIN_TOKEN || process.env.ADMIN_TOKEN || "", 3000); }
function adminCookieSignature() { const token = adminToken(); if (!token) return ""; return crypto.createHmac("sha256", token).update("tvf-os-admin-session-v1").digest("hex"); }
function cookieValue(req, name = "tvf_admin_session") { const cookieHeader = clean(req.headers.cookie || "", 6000); const cookies = cookieHeader.split(";").map((item) => item.trim()); const found = cookies.find((item) => item.startsWith(`${name}=`)); return found ? cleanEnvToken(decodeURIComponent(found.slice(name.length + 1)), 3000) : ""; }
function tokenFromRequest(req) { const expectedCookie = adminCookieSignature(); const receivedCookie = cookieValue(req); if (expectedCookie && receivedCookie && safeEqual(receivedCookie, expectedCookie)) return adminToken(); const authorization = clean(req.headers.authorization || "", 4000); if (authorization.toLowerCase().startsWith("bearer ")) { const bearer = cleanEnvToken(authorization.slice(7), 3000); if (bearer) return bearer; } return cleanEnvToken(req.headers["x-admin-token"] || "", 3000); }
function safeEqual(a, b) { if (!a || !b) return false; const left = Buffer.from(a); const right = Buffer.from(b); if (left.length !== right.length) return false; return crypto.timingSafeEqual(left, right); }
function requireAdmin(req) { const expected = adminToken(); if (!expected) throw Object.assign(new Error("Back-office non configure : ajoutez TVF_ADMIN_TOKEN dans Vercel."), { statusCode: 503, code: "ADMIN_TOKEN_MISSING" }); if (!safeEqual(tokenFromRequest(req), expected)) throw Object.assign(new Error("Acces admin refuse."), { statusCode: 401, code: "ADMIN_UNAUTHORIZED" }); }
function supabaseConfig() { const restUrl = normalizeSupabaseRestUrl(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL); const key = cleanEnvToken(process.env.SUPABASE_SERVICE_ROLE_KEY || "", 3000); if (!restUrl || !key) throw Object.assign(new Error("Supabase admin non configure : SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY sont requis."), { statusCode: 503, code: "SUPABASE_ADMIN_NOT_CONFIGURED" }); return { restUrl, key }; }
function supabaseHeaders(key, extra = {}) { const headers = { apikey: key, "Content-Type": "application/json", ...extra }; if (!key.startsWith("sb_")) headers.Authorization = `Bearer ${key}`; return headers; }
async function fetchWithTimeout(url, options = {}) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), OUTBOUND_TIMEOUT_MS); try { return await fetch(url, { ...options, signal: controller.signal }); } finally { clearTimeout(timeout); } }
async function supabaseRequest(path, options = {}) { const { restUrl, key } = supabaseConfig(); const response = await fetchWithTimeout(`${restUrl}/${path}`, { ...options, headers: supabaseHeaders(key, options.headers || {}) }); const text = await response.text(); if (!response.ok) throw Object.assign(new Error("Requete Supabase impossible."), { statusCode: 502, details: text }); return text ? JSON.parse(text) : null; }
function queryUrl(req) { return new URL(req.url, "https://admin.local"); }
function validateUuid(value, label = "Identifiant") { const cleaned = clean(value || "", 80); if (cleaned && !/^[0-9a-f-]{32,36}$/i.test(cleaned)) throw Object.assign(new Error(`${label} invalide.`), { statusCode: 400 }); return cleaned || null; }
function validateEnum(set, value, message) { if (value && !set.has(value)) throw Object.assign(new Error(message), { statusCode: 400 }); }
function dateTime(value) { const text = clean(value || "", 80); if (!text) return null; const time = new Date(text).getTime(); return Number.isNaN(time) ? null : new Date(time).toISOString(); }
function dateOnly(value) { const date = dateTime(value); return date ? date.slice(0, 10) : null; }
function arrayValue(value, max = 20) { if (Array.isArray(value)) return value.map((item) => clean(String(item || ""), 180)).filter(Boolean).slice(0, max); return clean(String(value || ""), 2000).split(/[;\n,]/).map((item) => clean(item, 180)).filter(Boolean).slice(0, max); }
function inferPriority(text) { const source = String(text || "").toLowerCase(); if (/urgent|bloque|retard|danger|demain|p1/.test(source)) return "P1"; if (/relance|rendez|signature|finance|mairie|p2/.test(source)) return "P2"; return "P3"; }
function taskAssistant(task = {}) { const due = task.due_at ? new Date(task.due_at).getTime() : 0; const overdue = due && due < Date.now() && !["done", "cancelled", "archive"].includes(task.status); const score = task.status === "done" ? 100 : overdue ? 25 : task.priority === "P1" ? 55 : 72; return { urgency_score: score, overdue: Boolean(overdue), summary: overdue ? "Tache en retard a traiter en priorite." : task.priority === "P1" ? "Tache prioritaire a suivre aujourd'hui." : "Tache sous controle.", next_actions: overdue ? ["Relancer le responsable", "Replanifier l'echeance"] : ["Verifier l'avancement", "Mettre a jour le statut"] }; }
function projectPayload(input, partial = false) { const status = clean(input.status || "", 80) || (!partial ? "active" : ""); const priority = clean(input.priority || "", 80) || (!partial ? inferPriority(`${input.title || ""} ${input.summary || ""}`) : ""); validateEnum(PROJECT_STATUSES, status, "Statut projet invalide."); validateEnum(PRIORITIES, priority, "Priorite projet invalide."); const payload = { project_key: clean(input.project_key || "", 120) || null, title: clean(input.title || "", 260), project_type: clean(input.project_type || "operation", 80), status, priority, pole: clean(input.pole || "Pilotage", 180), branch_id: validateUuid(input.branch_id || "", "Antenne"), owner_name: clean(input.owner_name || "", 180), summary: clean(input.summary || "", 1600), start_at: dateOnly(input.start_at), due_at: dateOnly(input.due_at), progress: Number(input.progress || 0), ai_summary: clean(input.ai_summary || input.summary || "", 1600) }; if (!partial && !payload.title) throw Object.assign(new Error("Titre projet requis."), { statusCode: 400 }); return Object.fromEntries(Object.entries(payload).filter(([key, value]) => (!partial || Object.prototype.hasOwnProperty.call(input, key)) && value !== "" && value !== undefined)); }
function taskPayload(input, partial = false) { const status = clean(input.status || "", 80) || (!partial ? "todo" : ""); const priority = clean(input.priority || "", 80) || (!partial ? inferPriority(`${input.title || ""} ${input.description || ""} ${input.summary || ""}`) : ""); validateEnum(TASK_STATUSES, status, "Statut tache invalide."); validateEnum(PRIORITIES, priority, "Priorite tache invalide."); const payload = { task_key: clean(input.task_key || "", 120) || null, project_id: validateUuid(input.project_id || "", "Projet"), related_object_type: clean(input.related_object_type || "none", 80), related_object_id: validateUuid(input.related_object_id || "", "Objet lie"), title: clean(input.title || "", 260), description: clean(input.description || input.summary || "", 1600), status, priority, pole: clean(input.pole || "Pilotage", 180), assigned_to: clean(input.assigned_to || "", 180), branch_id: validateUuid(input.branch_id || "", "Antenne"), start_at: dateTime(input.start_at), due_at: dateTime(input.due_at), completed_at: status === "done" ? (dateTime(input.completed_at) || new Date().toISOString()) : null, checklist: arrayValue(input.checklist || ""), ai_summary: clean(input.ai_summary || input.description || input.summary || "", 1600), automation_source: clean(input.automation_source || "", 160), created_by: clean(input.created_by || "TVF OS", 180) }; if (!partial && !payload.title) throw Object.assign(new Error("Titre tache requis."), { statusCode: 400 }); return Object.fromEntries(Object.entries(payload).filter(([key, value]) => (!partial || Object.prototype.hasOwnProperty.call(input, key) || key === "completed_at") && value !== "" && value !== undefined)); }
function eventPayload(input, partial = false) { const status = clean(input.status || "", 80) || (!partial ? "scheduled" : ""); validateEnum(EVENT_STATUSES, status, "Statut evenement invalide."); const payload = { event_key: clean(input.event_key || "", 120) || null, project_id: validateUuid(input.project_id || "", "Projet"), task_id: validateUuid(input.task_id || "", "Tache"), title: clean(input.title || "", 260), event_type: clean(input.event_type || "meeting", 80), status, starts_at: dateTime(input.starts_at) || (!partial ? new Date().toISOString() : null), ends_at: dateTime(input.ends_at), location: clean(input.location || "", 260), attendees: arrayValue(input.attendees || ""), organizer_name: clean(input.organizer_name || "", 180), branch_id: validateUuid(input.branch_id || "", "Antenne"), notes: clean(input.notes || input.summary || "", 1600), ai_summary: clean(input.ai_summary || input.notes || input.summary || "", 1600) }; if (!partial && !payload.title) throw Object.assign(new Error("Titre evenement requis."), { statusCode: 400 }); return Object.fromEntries(Object.entries(payload).filter(([key, value]) => (!partial || Object.prototype.hasOwnProperty.call(input, key)) && value !== "" && value !== undefined)); }
async function createRecord(table, payload) { const rows = await supabaseRequest(`${table}?select=*`, { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function updateRecord(table, id, payload) { const rows = await supabaseRequest(`${table}?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function listTable(req, table, statusSet, order = "updated_at.desc") { const url = queryUrl(req); const params = new URLSearchParams({ select: "*", order, limit: String(Math.min(Math.max(Number(url.searchParams.get("limit") || 240), 1), 700)) }); const status = clean(url.searchParams.get("status") || "", 80); const q = clean(url.searchParams.get("q") || "", 120).replace(/[*,()]/g, " "); const searchColumns = { work_projects: ["title", "summary", "pole", "owner_name"], work_tasks: ["title", "description", "pole", "assigned_to"], work_events: ["title", "notes", "location", "organizer_name"], work_automation_rules: ["name", "description", "trigger_type"] }; if (status && status !== "all" && statusSet?.has(status)) params.set("status", `eq.${status}`); if (q && searchColumns[table]) params.set("or", `(${searchColumns[table].map((column) => `${column}.ilike.*${q}*`).join(",")})`); return supabaseRequest(`${table}?${params.toString()}`); }
async function dashboard() { const [projects, tasks, events, rules] = await Promise.all([supabaseRequest("work_projects?select=*&limit=700"), supabaseRequest("work_tasks?select=*&limit=1200"), supabaseRequest("work_events?select=*&limit=700"), supabaseRequest("work_automation_rules?select=*&limit=200")]); const openTasks = tasks.filter((t) => !["done", "cancelled", "archive"].includes(t.status)); const overdue = openTasks.filter((t) => t.due_at && new Date(t.due_at).getTime() < Date.now()); return { active_projects: projects.filter((p) => p.status === "active").length, open_tasks: openTasks.length, overdue_tasks: overdue.length, today_events: events.filter((e) => e.starts_at && new Date(e.starts_at).toISOString().slice(0, 10) === new Date().toISOString().slice(0, 10)).length, active_rules: rules.filter((r) => r.status === "active").length, assistant: { summary: `${openTasks.length} tache(s) ouvertes, ${overdue.length} en retard, ${events.length} evenement(s).`, priorities: overdue.length ? ["Traiter les taches en retard", "Replanifier les echeances", "Alerter les responsables"] : ["Suivre les echeances", "Preparer les rendez-vous", "Maintenir les projets a jour"] } }; }
module.exports = async function handler(req, res) { if (req.method === "OPTIONS") { res.statusCode = 204; res.end(); return; } try { requireAdmin(req); if (req.method === "GET") { const entity = clean(queryUrl(req).searchParams.get("entity") || "dashboard", 80); if (entity === "dashboard") return sendJson(res, 200, { ok: true, dashboard: await dashboard() }); if (entity === "projects") return sendJson(res, 200, { ok: true, projects: await listTable(req, "work_projects", PROJECT_STATUSES, "updated_at.desc") }); if (entity === "tasks") { const tasks = await listTable(req, "work_tasks", TASK_STATUSES, "due_at.asc"); return sendJson(res, 200, { ok: true, tasks: tasks.map((task) => ({ ...task, assistant: taskAssistant(task) })) }); } if (entity === "events") return sendJson(res, 200, { ok: true, events: await listTable(req, "work_events", EVENT_STATUSES, "starts_at.asc") }); if (entity === "rules") return sendJson(res, 200, { ok: true, rules: await listTable(req, "work_automation_rules", RULE_STATUSES, "updated_at.desc") }); if (entity === "activity") return sendJson(res, 200, { ok: true, activity: await listTable(req, "work_activity_log", null, "created_at.desc") }); throw Object.assign(new Error("Entite inconnue."), { statusCode: 400 }); }
    const input = await readJsonBody(req); const type = clean(input.type || "task", 80); if (req.method === "POST") { if (type === "project") return sendJson(res, 201, { ok: true, project: await createRecord("work_projects", projectPayload(input)) }); if (type === "task") return sendJson(res, 201, { ok: true, task: await createRecord("work_tasks", taskPayload(input)) }); if (type === "event") return sendJson(res, 201, { ok: true, event: await createRecord("work_events", eventPayload(input)) }); }
    if (req.method === "PATCH") { const id = validateUuid(input.id || "", "Identifiant"); if (type === "project") return sendJson(res, 200, { ok: true, project: await updateRecord("work_projects", id, projectPayload(input, true)) }); if (type === "task") return sendJson(res, 200, { ok: true, task: await updateRecord("work_tasks", id, taskPayload(input, true)) }); if (type === "event") return sendJson(res, 200, { ok: true, event: await updateRecord("work_events", id, eventPayload(input, true)) }); }
    sendJson(res, 405, { ok: false, error: "Methode non autorisee." }); } catch (error) { const statusCode = error.statusCode || 500; sendJson(res, statusCode, { ok: false, error: statusCode >= 500 ? "Module Taches & Agenda indisponible pour le moment." : error.message, code: error.code || undefined, details: process.env.NODE_ENV === "development" ? error.details || error.message : undefined }); } };
module.exports._private = { normalizeSupabaseRestUrl, inferPriority, taskAssistant, projectPayload, taskPayload, eventPayload };
