const crypto = require("crypto");

const OUTBOUND_TIMEOUT_MS = Number(process.env.TVF_OUTBOUND_TIMEOUT_MS || 9000);
const EMAIL_STATUSES = new Set(["new", "analyzed", "to_reply", "waiting_info", "converted", "closed", "archive"]);
const PRIORITIES = new Set(["P1", "P2", "P3"]);
const CATEGORIES = new Set(["general", "owner", "materials", "local_authority", "company", "volunteer", "finance", "press", "risk"]);
const TASK_STATUSES = new Set(["todo", "doing", "waiting", "done", "cancelled", "archive"]);
const SUGGESTION_STATUSES = new Set(["proposed", "accepted", "modified", "rejected", "applied", "archive"]);

function sendJson(res, statusCode, payload) { res.statusCode = statusCode; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("Cache-Control", "no-store"); res.end(JSON.stringify(payload)); }
function clean(value, max = 1200) { if (typeof value !== "string") return ""; return value.replace(/\s+/g, " ").trim().slice(0, max); }
function cleanEnvToken(value, max = 3000) { return clean(value || "", max).replace(/^[`'\",;]+|[`'\",;]+$/g, "").replace(/\s+/g, ""); }
function cleanEnvUrl(value) { return clean(value || "", 600).replace(/^[`'\",;]+|[`'\",;]+$/g, ""); }
function normalizeSupabaseRestUrl(rawUrl) { const cleaned = cleanEnvUrl(rawUrl).replace(/\/+$/, ""); if (!cleaned) return ""; return cleaned.endsWith("/rest/v1") ? cleaned : `${cleaned}/rest/v1`; }
async function readJsonBody(req) { let body = ""; for await (const chunk of req) { body += chunk; if (body.length > 120 * 1024) throw Object.assign(new Error("Payload trop volumineux."), { statusCode: 413 }); } if (!body) return {}; try { return JSON.parse(body); } catch { throw Object.assign(new Error("JSON invalide."), { statusCode: 400 }); } }
function adminToken() { return cleanEnvToken(process.env.TVF_ADMIN_TOKEN || process.env.ADMIN_TOKEN || "", 3000); }
function tokenFromRequest(req) { const authorization = clean(req.headers.authorization || "", 4000); if (authorization.toLowerCase().startsWith("bearer ")) return cleanEnvToken(authorization.slice(7), 3000); return cleanEnvToken(req.headers["x-admin-token"] || "", 3000); }
function safeEqual(a, b) { if (!a || !b) return false; const left = Buffer.from(a); const right = Buffer.from(b); if (left.length !== right.length) return false; return crypto.timingSafeEqual(left, right); }
function requireAdmin(req) { const expected = adminToken(); if (!expected) throw Object.assign(new Error("Back-office non configure : ajoutez TVF_ADMIN_TOKEN dans Vercel."), { statusCode: 503, code: "ADMIN_TOKEN_MISSING" }); if (!safeEqual(tokenFromRequest(req), expected)) throw Object.assign(new Error("Acces admin refuse."), { statusCode: 401, code: "ADMIN_UNAUTHORIZED" }); }
function supabaseConfig() { const restUrl = normalizeSupabaseRestUrl(process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL); const key = cleanEnvToken(process.env.SUPABASE_SERVICE_ROLE_KEY || "", 3000); if (!restUrl || !key) throw Object.assign(new Error("Supabase admin non configure : SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY sont requis."), { statusCode: 503, code: "SUPABASE_ADMIN_NOT_CONFIGURED" }); return { restUrl, key }; }
function supabaseHeaders(key, extra = {}) { const headers = { apikey: key, "Content-Type": "application/json", ...extra }; if (!key.startsWith("sb_")) headers.Authorization = `Bearer ${key}`; return headers; }
async function fetchWithTimeout(url, options = {}) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), OUTBOUND_TIMEOUT_MS); try { return await fetch(url, { ...options, signal: controller.signal }); } finally { clearTimeout(timeout); } }
async function supabaseRequest(path, options = {}) { const { restUrl, key } = supabaseConfig(); const response = await fetchWithTimeout(`${restUrl}/${path}`, { ...options, headers: supabaseHeaders(key, options.headers || {}) }); const text = await response.text(); if (!response.ok) throw Object.assign(new Error("Requete Supabase impossible."), { statusCode: 502, details: text, path }); return text ? JSON.parse(text) : null; }
function queryUrl(req) { return new URL(req.url, "https://admin.local"); }
function validateUuid(value, label = "Identifiant") { const cleaned = clean(value || "", 80); if (cleaned && !/^[0-9a-f-]{32,36}$/i.test(cleaned)) throw Object.assign(new Error(`${label} invalide.`), { statusCode: 400 }); return cleaned || null; }
function validateEnum(set, value, message) { if (value && !set.has(value)) throw Object.assign(new Error(message), { statusCode: 400 }); }
function dateValue(value) { const text = clean(value || "", 80); if (!text) return null; const time = new Date(text).getTime(); return Number.isNaN(time) ? null : new Date(time).toISOString(); }
function arrayValue(value, max = 20) { if (Array.isArray(value)) return value.map((item) => clean(String(item || ""), 180)).filter(Boolean).slice(0, max); return clean(String(value || ""), 2000).split(/[;\n,]/).map((item) => clean(item, 180)).filter(Boolean).slice(0, max); }
function normalize(value) { return String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function inferCategory(text) { const source = normalize(text); if (/materiau|materiaux|reemploi|stock|mobilier|palette|bois/.test(source)) return "materials"; if (/mairie|commune|metropole|epci|collectivite|territoire|elu/.test(source)) return "local_authority"; if (/proprietaire|logement|immeuble|bien vacant|local vacant|friche|terrain/.test(source)) return "owner"; if (/entreprise|rse|partenariat|mecenat de competence|artisan/.test(source)) return "company"; if (/benevole|volontaire|association|insertion|chantier/.test(source)) return "volunteer"; if (/finance|mecene|fondation|subvention|appel a projet/.test(source)) return "finance"; if (/presse|journaliste|media|interview/.test(source)) return "press"; if (/rgpd|danger|securite|incident|assurance|risque/.test(source)) return "risk"; return "general"; }
function inferPriority(text) { const source = normalize(text); if (/urgent|danger|securite|blocage|demain|sinistre|critique/.test(source)) return "P1"; if (/relance|rendez|mairie|commune|finance|signature|partenaire|echeance/.test(source)) return "P2"; return "P3"; }
function poleFromCategory(category) { return { general: "Accueil & orientation", owner: "Habitat Vivant", materials: "Materiautheque Solidaire", local_authority: "Collectivites & Territoires", company: "Entreprises & Partenariats", volunteer: "Solidarite & Insertion", finance: "Financement & Mecenat", press: "Communication & Plaidoyer", risk: "Gouvernance & Conformite" }[category] || "Accueil & orientation"; }
function missingPieces(category) { return { owner: ["adresse precise", "photos", "autorisation de visite", "contact proprietaire"], materials: ["liste des materiaux", "quantites", "photos", "delai d'enlevement"], local_authority: ["territoire concerne", "interlocuteur referent", "besoin prioritaire", "calendrier"], company: ["type de contribution", "contact decisionnaire", "contraintes logistiques"], volunteer: ["disponibilites", "competences", "zone d'intervention"], finance: ["dispositif vise", "montant indicatif", "echeance"], press: ["angle souhaite", "date limite", "support"], risk: ["preuve", "personne responsable", "echeance de correction"] }[category] || ["contexte", "contact", "territoire", "delai attendu"]; }
function dueDate(priority) { const date = new Date(); date.setDate(date.getDate() + (priority === "P1" ? 1 : priority === "P2" ? 2 : 5)); return date.toISOString(); }
function buildDraft(input, analysis) { return `Bonjour,\n\nMerci pour votre message. Nous l'avons bien recu et l'avons oriente vers le pole ${analysis.pole}.\n\nPour avancer, pouvez-vous nous transmettre les elements suivants :\n- ${analysis.missing_pieces.join("\n- ")}\n\nUne fois ces informations recues, nous pourrons qualifier la suite a donner.\n\nCordialement,\nTerritoires Vivants France`; }
function analyzeEmail(input) { const text = [input.subject, input.body_text, input.body, input.message, input.from_email, input.from_name].join(" "); const category = inferCategory(text); const priority = inferPriority(text); const pole = poleFromCategory(category); const missing = missingPieces(category); const nextAction = priority === "P1" ? "Traiter en priorite et alerter le responsable" : "Verifier les pieces puis proposer une reponse"; const analysis = { category, priority, pole, missing_pieces: missing, next_action: nextAction, next_action_due_at: dueDate(priority), ai_confidence: category === "general" ? 0.58 : 0.78, ai_summary: `${pole} - ${category}. Priorite ${priority}. ${nextAction}.`, needs_case: category !== "general" || priority !== "P3" }; analysis.draft_response = buildDraft(input, analysis); analysis.tasks = [nextAction, "Verifier le contact et rattacher au CRM", "Valider le brouillon avant envoi"]; return analysis; }
function emailPayload(input, partial = false) { const analysis = analyzeEmail(input); const status = clean(input.status || "", 80) || (!partial ? "analyzed" : ""); const priority = clean(input.priority || "", 80) || (!partial ? analysis.priority : ""); const category = clean(input.category || "", 80) || (!partial ? analysis.category : ""); validateEnum(EMAIL_STATUSES, status, "Statut e-mail invalide."); validateEnum(PRIORITIES, priority, "Priorite e-mail invalide."); validateEnum(CATEGORIES, category, "Categorie e-mail invalide."); const payload = { external_message_id: clean(input.external_message_id || "", 220) || null, thread_key: clean(input.thread_key || input.external_message_id || "", 220) || null, provider: clean(input.provider || "manual", 80), direction: clean(input.direction || "inbound", 20), from_email: clean(input.from_email || input.email || "", 220).toLowerCase(), from_name: clean(input.from_name || input.full_name || "", 180), to_email: clean(input.to_email || "contact@territoiresvivantsfrance.fr", 220), subject: clean(input.subject || "Sans objet", 260), body_text: clean(input.body_text || input.body || input.message || "", 9000), received_at: dateValue(input.received_at) || (!partial ? new Date().toISOString() : null), status, priority, category, pole: clean(input.pole || analysis.pole, 180), assigned_to: clean(input.assigned_to || "", 180) || null, contact_id: validateUuid(input.contact_id || "", "Contact"), case_id: validateUuid(input.case_id || "", "Dossier"), ai_summary: clean(input.ai_summary || analysis.ai_summary, 1600), ai_confidence: Number(input.ai_confidence || analysis.ai_confidence), missing_pieces: arrayValue(input.missing_pieces || analysis.missing_pieces), draft_response: clean(input.draft_response || analysis.draft_response, 4000), next_action: clean(input.next_action || analysis.next_action, 260), next_action_due_at: dateValue(input.next_action_due_at) || (!partial ? analysis.next_action_due_at : null), source_payload: input.source_payload && typeof input.source_payload === "object" ? input.source_payload : {} };
  if (!partial && (!payload.from_email || !payload.body_text)) throw Object.assign(new Error("E-mail expediteur et contenu requis."), { statusCode: 400 });
  return Object.fromEntries(Object.entries(payload).filter(([key, value]) => !partial || Object.prototype.hasOwnProperty.call(input, key) || ["ai_summary", "ai_confidence", "missing_pieces", "draft_response", "next_action", "next_action_due_at"].includes(key)).filter(([key, value]) => (!partial || Object.prototype.hasOwnProperty.call(input, key)) && value !== "" && value !== undefined)); }
function taskPayload(input, partial = false) { const status = clean(input.status || "", 80) || (!partial ? "todo" : ""); const priority = clean(input.priority || "", 80) || (!partial ? "P3" : ""); validateEnum(TASK_STATUSES, status, "Statut tache invalide."); validateEnum(PRIORITIES, priority, "Priorite tache invalide."); const payload = { email_message_id: validateUuid(input.email_message_id || "", "E-mail"), title: clean(input.title || "Verifier e-mail", 260), description: clean(input.description || "", 1200), assigned_to: clean(input.assigned_to || "", 180), status, priority, due_at: dateValue(input.due_at), created_by: clean(input.created_by || "TVF OS", 180) }; if (!partial && !payload.email_message_id) throw Object.assign(new Error("E-mail requis."), { statusCode: 400 }); return Object.fromEntries(Object.entries(payload).filter(([key, value]) => (!partial || Object.prototype.hasOwnProperty.call(input, key)) && value !== "" && value !== undefined)); }
function suggestionPayload(email, analysis, type = "triage") { return { email_message_id: email.id, suggestion_type: type, title: type === "draft_response" ? "Brouillon de reponse" : "Triage IA e-mail", payload: { priority: analysis.priority, category: analysis.category, pole: analysis.pole, missing_pieces: analysis.missing_pieces, draft_response: analysis.draft_response, tasks: analysis.tasks, needs_case: analysis.needs_case }, confidence: analysis.ai_confidence, status: "proposed" }; }
async function createRecord(table, payload) { const rows = await supabaseRequest(`${table}?select=*`, { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function updateRecord(table, id, payload) { const rows = await supabaseRequest(`${table}?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(payload) }); return rows?.[0] || null; }
async function listTable(req, table, order = "created_at.desc", set = null) { const url = queryUrl(req); const params = new URLSearchParams({ select: "*", order, limit: String(Math.min(Math.max(Number(url.searchParams.get("limit") || 160), 1), 500)) }); const status = clean(url.searchParams.get("status") || "", 80); const q = clean(url.searchParams.get("q") || "", 120).replace(/[*,()]/g, " "); if (status && status !== "all" && (!set || set.has(status))) params.set("status", `eq.${status}`); if (q && table === "email_messages") params.set("or", `(from_email.ilike.*${q}*,from_name.ilike.*${q}*,subject.ilike.*${q}*,body_text.ilike.*${q}*,pole.ilike.*${q}*)`); return supabaseRequest(`${table}?${params.toString()}`); }
async function dashboard() { const [messages, suggestions, tasks] = await Promise.all([supabaseRequest("email_messages?select=*&limit=800"), supabaseRequest("email_ai_suggestions?select=*&limit=800"), supabaseRequest("email_tasks?select=*&limit=800")]); return { total_messages: messages.length, open_messages: messages.filter((m) => !["closed", "archive"].includes(m.status)).length, to_reply: messages.filter((m) => ["new", "analyzed", "to_reply", "waiting_info"].includes(m.status)).length, urgent: messages.filter((m) => m.priority === "P1" && !["closed", "archive"].includes(m.status)).length, pending_suggestions: suggestions.filter((s) => s.status === "proposed").length, open_tasks: tasks.filter((t) => !["done", "cancelled", "archive"].includes(t.status)).length, assistant: { summary: `${messages.length} e-mail(s), ${suggestions.filter((s) => s.status === "proposed").length} suggestion(s), ${tasks.filter((t) => t.status === "todo").length} tache(s) a traiter.`, priorities: ["Valider les brouillons avant envoi", "Convertir les e-mails qualifiees en demandes", "Suivre les pieces manquantes"] } }; }
async function createEmail(input) { const payload = emailPayload(input); const email = await createRecord("email_messages", payload); const analysis = analyzeEmail(payload); await createRecord("email_workflow_events", { email_message_id: email.id, event_type: "analyzed", event_label: "E-mail analyse par TVF OS", actor_label: "TVF OS", payload: analysis }); const suggestion = await createRecord("email_ai_suggestions", suggestionPayload(email, analysis, "triage")); const task = await createRecord("email_tasks", { email_message_id: email.id, title: analysis.next_action, description: `Pieces : ${analysis.missing_pieces.join(", ")}`, assigned_to: payload.assigned_to || "A attribuer", status: "todo", priority: analysis.priority, due_at: analysis.next_action_due_at, created_by: "TVF OS" }); return { email, suggestion, task, analysis }; }
async function convertToRequest(input) { const id = validateUuid(input.id || input.email_message_id || "", "E-mail"); if (!id) throw Object.assign(new Error("E-mail requis."), { statusCode: 400 }); const rows = await supabaseRequest(`email_messages?${new URLSearchParams({ select: "*", id: `eq.${id}` }).toString()}`); const email = rows?.[0]; if (!email) throw Object.assign(new Error("E-mail introuvable."), { statusCode: 404 }); const contactPayload = { full_name: email.from_name || email.from_email, email: email.from_email, subject: email.subject, message: email.body_text, channel: "email", status: "nouveau", priority: email.priority === "P1" ? "urgente" : email.priority === "P2" ? "haute" : "normale", category: "demande-generale", pole: email.pole, internal_notes: `Converti depuis e-mail ${email.id}. ${email.ai_summary || ""}`, missing_pieces: email.missing_pieces, next_action: email.next_action, next_action_due_at: email.next_action_due_at };
  const contact = await createRecord("contacts", contactPayload); const updated = await updateRecord("email_messages", id, { status: "converted", contact_id: contact.id }); await createRecord("email_workflow_events", { email_message_id: id, event_type: "converted", event_label: "Converti en demande entrante", actor_label: clean(input.actor_label || "TVF OS", 180), payload: { contact_id: contact.id } }); return { email: updated, contact }; }
async function patchSuggestion(input) { const id = validateUuid(input.id || "", "Suggestion"); if (!id) throw Object.assign(new Error("Suggestion requise."), { statusCode: 400 }); const status = clean(input.status || "", 80); validateEnum(SUGGESTION_STATUSES, status, "Statut suggestion invalide."); return updateRecord("email_ai_suggestions", id, { status, reviewed_by: clean(input.reviewed_by || "TVF OS", 180), reviewed_at: new Date().toISOString(), payload: input.payload && typeof input.payload === "object" ? input.payload : undefined }); }
module.exports = async function handler(req, res) { if (req.method === "OPTIONS") { res.statusCode = 204; res.end(); return; } try { requireAdmin(req); if (req.method === "GET") { const entity = clean(queryUrl(req).searchParams.get("entity") || "dashboard", 80); if (entity === "dashboard") return sendJson(res, 200, { ok: true, dashboard: await dashboard() }); if (entity === "messages") return sendJson(res, 200, { ok: true, messages: await listTable(req, "email_messages", "received_at.desc", EMAIL_STATUSES) }); if (entity === "suggestions") return sendJson(res, 200, { ok: true, suggestions: await listTable(req, "email_ai_suggestions", "created_at.desc", SUGGESTION_STATUSES) }); if (entity === "tasks") return sendJson(res, 200, { ok: true, tasks: await listTable(req, "email_tasks", "created_at.desc", TASK_STATUSES) }); if (entity === "events") return sendJson(res, 200, { ok: true, events: await listTable(req, "email_workflow_events", "created_at.desc") }); throw Object.assign(new Error("Entite inconnue."), { statusCode: 400 }); }
    const input = await readJsonBody(req); const type = clean(input.type || "email", 80); if (req.method === "POST") { if (type === "email") return sendJson(res, 201, { ok: true, ...(await createEmail(input)) }); if (type === "task") return sendJson(res, 201, { ok: true, task: await createRecord("email_tasks", taskPayload(input)) }); if (type === "convert_request") return sendJson(res, 201, { ok: true, ...(await convertToRequest(input)) }); }
    if (req.method === "PATCH") { const id = validateUuid(input.id || "", "Identifiant"); if (type === "email") return sendJson(res, 200, { ok: true, email: await updateRecord("email_messages", id, emailPayload(input, true)) }); if (type === "task") return sendJson(res, 200, { ok: true, task: await updateRecord("email_tasks", id, taskPayload(input, true)) }); if (type === "suggestion") return sendJson(res, 200, { ok: true, suggestion: await patchSuggestion(input) }); }
    sendJson(res, 405, { ok: false, error: "Methode non autorisee." }); } catch (error) { const statusCode = error.statusCode || 500; sendJson(res, statusCode, { ok: false, error: statusCode >= 500 ? "Module e-mails indisponible pour le moment." : error.message, code: error.code || undefined, details: process.env.NODE_ENV === "development" ? error.details || error.message : undefined }); } };
module.exports._private = { normalizeSupabaseRestUrl, inferCategory, inferPriority, poleFromCategory, missingPieces, analyzeEmail, emailPayload, taskPayload };
